// Generated by tools/gen_catalog.py
window.CHECKMATELA_CATALOG = [
  {
    "id": "king-sicilian-onyx-tux",
    "name": "The Sicilian",
    "tag": "Onyx Tuxedo",
    "category": "King · Men",
    "price": 895,
    "image": "assets/img/products/sicilian-onyx-tux.jpg",
    "page": "king.html",
    "sizes": [
      "36R",
      "38R",
      "40R",
      "42R",
      "44R",
      "46R"
    ],
    "color": "Black",
    "pattern": "Solid",
    "style": "Tuxedo",
    "occasion": [
      "Black tie",
      "Wedding",
      "Prom"
    ],
    "description": "A considered opening for weddings, celebrations, and evenings worth dressing for. Discover a silhouette with presence, from the first entrance to the last dance."
  },
  {
    "id": "king-ruy-lopez-three-piece",
    "name": "The Ruy Lopez",
    "tag": "Onyx Three-Piece",
    "category": "King · Men",
    "price": 975,
    "image": "assets/img/products/ruy-lopez-three-piece.jpg",
    "page": "king.html",
    "sizes": [
      "36R",
      "38R",
      "40R",
      "42R",
      "44R",
      "46R"
    ],
    "color": "Black",
    "pattern": "Solid",
    "style": "Three-piece",
    "occasion": [
      "Wedding",
      "Business",
      "Formal"
    ],
    "description": "A considered opening for weddings, celebrations, and evenings worth dressing for. Discover a silhouette with presence, from the first entrance to the last dance."
  },
  {
    "id": "king-caro-kann-navy-plaid",
    "name": "The Caro-Kann",
    "tag": "Midnight Plaid",
    "category": "King · Men",
    "price": 850,
    "image": "assets/img/products/caro-kann-navy-plaid.jpg",
    "page": "king.html",
    "sizes": [
      "36R",
      "38R",
      "40R",
      "42R",
      "44R",
      "46R"
    ],
    "color": "Navy",
    "pattern": "Plaid",
    "style": "Three-piece",
    "occasion": [
      "Business",
      "Wedding",
      "Formal"
    ],
    "description": "A considered opening for weddings, celebrations, and evenings worth dressing for. Discover a silhouette with presence, from the first entrance to the last dance."
  },
  {
    "id": "king-kings-gambit-royal-plaid",
    "name": "The King's Gambit",
    "tag": "Royal Plaid Three-Piece",
    "category": "King · Men",
    "price": 925,
    "image": "assets/img/products/kings-gambit-royal-plaid.jpg",
    "page": "king.html",
    "sizes": [
      "36R",
      "38R",
      "40R",
      "42R",
      "44R",
      "46R"
    ],
    "color": "Blue",
    "pattern": "Plaid",
    "style": "Three-piece",
    "occasion": [
      "Wedding",
      "Prom",
      "Formal"
    ],
    "description": "A considered opening for weddings, celebrations, and evenings worth dressing for. Discover a silhouette with presence, from the first entrance to the last dance."
  },
  {
    "id": "king-english-opening-charcoal",
    "name": "The English Opening",
    "tag": "Charcoal Classic",
    "category": "King · Men",
    "price": 795,
    "image": "assets/img/products/english-opening-charcoal.jpg",
    "page": "king.html",
    "sizes": [
      "36R",
      "38R",
      "40R",
      "42R",
      "44R",
      "46R"
    ],
    "color": "Grey",
    "pattern": "Solid",
    "style": "Two-piece",
    "occasion": [
      "Business",
      "Formal"
    ],
    "description": "A considered opening for weddings, celebrations, and evenings worth dressing for. Discover a silhouette with presence, from the first entrance to the last dance."
  },
  {
    "id": "king-queens-gambit-graphite",
    "name": "The Queen's Gambit",
    "tag": "Graphite Shawl",
    "category": "King · Men",
    "price": 910,
    "image": "assets/img/products/queens-gambit-graphite.jpg",
    "page": "king.html",
    "sizes": [
      "36R",
      "38R",
      "40R",
      "42R",
      "44R",
      "46R"
    ],
    "color": "Grey",
    "pattern": "Solid",
    "style": "Tuxedo",
    "occasion": [
      "Black tie",
      "Prom"
    ],
    "description": "A considered opening for weddings, celebrations, and evenings worth dressing for. Discover a silhouette with presence, from the first entrance to the last dance."
  },
  {
    "id": "king-london-system-stone",
    "name": "The London System",
    "tag": "Stone Three-Piece",
    "category": "King · Men",
    "price": 860,
    "image": "assets/img/products/london-system-stone.jpg",
    "page": "king.html",
    "sizes": [
      "36R",
      "38R",
      "40R",
      "42R",
      "44R",
      "46R"
    ],
    "color": "Cream",
    "pattern": "Solid",
    "style": "Three-piece",
    "occasion": [
      "Wedding",
      "Summer"
    ],
    "description": "A considered opening for weddings, celebrations, and evenings worth dressing for. Discover a silhouette with presence, from the first entrance to the last dance."
  },
  {
    "id": "king-italian-game-bordeaux",
    "name": "The Italian Game",
    "tag": "Bordeaux Tuxedo",
    "category": "King · Men",
    "price": 895,
    "image": "assets/img/products/italian-game-bordeaux.jpg",
    "page": "king.html",
    "sizes": [
      "36R",
      "38R",
      "40R",
      "42R",
      "44R",
      "46R"
    ],
    "color": "Burgundy",
    "pattern": "Solid",
    "style": "Tuxedo",
    "occasion": [
      "Black tie",
      "Prom",
      "Wedding"
    ],
    "description": "A considered opening for weddings, celebrations, and evenings worth dressing for. Discover a silhouette with presence, from the first entrance to the last dance."
  },
  {
    "id": "king-french-defense-slate-check",
    "name": "The French Defense",
    "tag": "Slate Check",
    "category": "King · Men",
    "price": 820,
    "image": "assets/img/products/french-defense-slate-check.jpg",
    "page": "king.html",
    "sizes": [
      "36R",
      "38R",
      "40R",
      "42R",
      "44R",
      "46R"
    ],
    "color": "Blue",
    "pattern": "Check",
    "style": "Three-piece",
    "occasion": [
      "Business",
      "Formal"
    ],
    "description": "A considered opening for weddings, celebrations, and evenings worth dressing for. Discover a silhouette with presence, from the first entrance to the last dance."
  },
  {
    "id": "king-scotch-game-dove-grey",
    "name": "The Scotch Game",
    "tag": "Dove Grey Three-Piece",
    "category": "King · Men",
    "price": 840,
    "image": "assets/img/products/scotch-game-dove-grey.jpg",
    "page": "king.html",
    "sizes": [
      "36R",
      "38R",
      "40R",
      "42R",
      "44R",
      "46R"
    ],
    "color": "Grey",
    "pattern": "Solid",
    "style": "Three-piece",
    "occasion": [
      "Wedding",
      "Summer",
      "Formal"
    ],
    "description": "A considered opening for weddings, celebrations, and evenings worth dressing for. Discover a silhouette with presence, from the first entrance to the last dance."
  },
  {
    "id": "pawn-slim-fit-black",
    "name": "Black Slim Fit",
    "tag": "Slim Fit",
    "category": "Pawn · Kids",
    "price": 129,
    "image": "assets/img/pawn/slim-fit/black/model-1.jpg",
    "images": [
      "assets/img/pawn/slim-fit/black/model-1.jpg",
      "assets/img/pawn/slim-fit/black/model-2.jpg",
      "assets/img/pawn/slim-fit/black/model-3.jpg",
      "assets/img/pawn/slim-fit/black/model-4.jpg",
      "assets/img/pawn/slim-fit/black/plain-1.jpg",
      "assets/img/pawn/slim-fit/black/plain-2.jpg"
    ],
    "page": "pawn-slim-fit.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-slim-fit-navy",
    "name": "Navy Slim Fit",
    "tag": "Slim Fit",
    "category": "Pawn · Kids",
    "price": 129,
    "image": "assets/img/pawn/slim-fit/navy/model-1.jpg",
    "images": [
      "assets/img/pawn/slim-fit/navy/model-1.jpg",
      "assets/img/pawn/slim-fit/navy/model-2.jpg",
      "assets/img/pawn/slim-fit/navy/model-3.jpg",
      "assets/img/pawn/slim-fit/navy/model-4.jpg",
      "assets/img/pawn/slim-fit/navy/plain-1.jpg",
      "assets/img/pawn/slim-fit/navy/plain-2.jpg"
    ],
    "page": "pawn-slim-fit.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-slim-fit-charcoal",
    "name": "Charcoal Slim Fit",
    "tag": "Slim Fit",
    "category": "Pawn · Kids",
    "price": 129,
    "image": "assets/img/pawn/slim-fit/charcoal/model-1.jpg",
    "images": [
      "assets/img/pawn/slim-fit/charcoal/model-1.jpg",
      "assets/img/pawn/slim-fit/charcoal/model-2.jpg",
      "assets/img/pawn/slim-fit/charcoal/model-3.jpg",
      "assets/img/pawn/slim-fit/charcoal/model-4.jpg",
      "assets/img/pawn/slim-fit/charcoal/plain-1.jpg",
      "assets/img/pawn/slim-fit/charcoal/plain-2.jpg"
    ],
    "page": "pawn-slim-fit.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-slim-fit-light-gray",
    "name": "Light Gray Slim Fit",
    "tag": "Slim Fit",
    "category": "Pawn · Kids",
    "price": 129,
    "image": "assets/img/pawn/slim-fit/light-gray/model-1.jpg",
    "images": [
      "assets/img/pawn/slim-fit/light-gray/model-1.jpg",
      "assets/img/pawn/slim-fit/light-gray/model-2.jpg",
      "assets/img/pawn/slim-fit/light-gray/model-3.jpg",
      "assets/img/pawn/slim-fit/light-gray/model-4.jpg",
      "assets/img/pawn/slim-fit/light-gray/plain-1.jpg",
      "assets/img/pawn/slim-fit/light-gray/plain-2.jpg"
    ],
    "page": "pawn-slim-fit.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-slim-fit-medium-gray",
    "name": "Medium Gray Slim Fit",
    "tag": "Slim Fit",
    "category": "Pawn · Kids",
    "price": 129,
    "image": "assets/img/pawn/slim-fit/medium-gray/model-1.jpg",
    "images": [
      "assets/img/pawn/slim-fit/medium-gray/model-1.jpg",
      "assets/img/pawn/slim-fit/medium-gray/model-2.jpg",
      "assets/img/pawn/slim-fit/medium-gray/model-3.jpg",
      "assets/img/pawn/slim-fit/medium-gray/model-4.jpg",
      "assets/img/pawn/slim-fit/medium-gray/plain-1.jpg",
      "assets/img/pawn/slim-fit/medium-gray/plain-2.jpg"
    ],
    "page": "pawn-slim-fit.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-slim-fit-white",
    "name": "White Slim Fit",
    "tag": "Slim Fit",
    "category": "Pawn · Kids",
    "price": 129,
    "image": "assets/img/pawn/slim-fit/white/model-1.jpg",
    "images": [
      "assets/img/pawn/slim-fit/white/model-1.jpg",
      "assets/img/pawn/slim-fit/white/model-2.jpg",
      "assets/img/pawn/slim-fit/white/model-3.jpg",
      "assets/img/pawn/slim-fit/white/model-4.jpg",
      "assets/img/pawn/slim-fit/white/plain-1.jpg",
      "assets/img/pawn/slim-fit/white/plain-2.jpg"
    ],
    "page": "pawn-slim-fit.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-slim-fit-beige-khaki",
    "name": "Beige Khaki Slim Fit",
    "tag": "Slim Fit",
    "category": "Pawn · Kids",
    "price": 129,
    "image": "assets/img/pawn/slim-fit/beige-khaki/model-1.jpg",
    "images": [
      "assets/img/pawn/slim-fit/beige-khaki/model-1.jpg",
      "assets/img/pawn/slim-fit/beige-khaki/model-2.jpg",
      "assets/img/pawn/slim-fit/beige-khaki/model-3.jpg",
      "assets/img/pawn/slim-fit/beige-khaki/model-4.jpg",
      "assets/img/pawn/slim-fit/beige-khaki/plain-1.jpg",
      "assets/img/pawn/slim-fit/beige-khaki/plain-2.jpg"
    ],
    "page": "pawn-slim-fit.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-slim-fit-khaki",
    "name": "Khaki Slim Fit",
    "tag": "Slim Fit",
    "category": "Pawn · Kids",
    "price": 129,
    "image": "assets/img/pawn/slim-fit/khaki/model-1.jpg",
    "images": [
      "assets/img/pawn/slim-fit/khaki/model-1.jpg",
      "assets/img/pawn/slim-fit/khaki/model-2.jpg",
      "assets/img/pawn/slim-fit/khaki/model-3.jpg",
      "assets/img/pawn/slim-fit/khaki/model-4.jpg",
      "assets/img/pawn/slim-fit/khaki/plain-1.jpg",
      "assets/img/pawn/slim-fit/khaki/plain-2.jpg"
    ],
    "page": "pawn-slim-fit.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-slim-fit-light-navy",
    "name": "Light Navy Slim Fit",
    "tag": "Slim Fit",
    "category": "Pawn · Kids",
    "price": 129,
    "image": "assets/img/pawn/slim-fit/light-navy/model-1.jpg",
    "images": [
      "assets/img/pawn/slim-fit/light-navy/model-1.jpg",
      "assets/img/pawn/slim-fit/light-navy/model-2.jpg",
      "assets/img/pawn/slim-fit/light-navy/model-3.jpg",
      "assets/img/pawn/slim-fit/light-navy/model-4.jpg",
      "assets/img/pawn/slim-fit/light-navy/plain-1.jpg",
      "assets/img/pawn/slim-fit/light-navy/plain-2.jpg"
    ],
    "page": "pawn-slim-fit.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-slim-fit-royal-blue",
    "name": "Royal Blue Slim Fit",
    "tag": "Slim Fit",
    "category": "Pawn · Kids",
    "price": 129,
    "image": "assets/img/pawn/slim-fit/royal-blue/model-1.jpg",
    "images": [
      "assets/img/pawn/slim-fit/royal-blue/model-1.jpg",
      "assets/img/pawn/slim-fit/royal-blue/model-2.jpg",
      "assets/img/pawn/slim-fit/royal-blue/model-3.jpg",
      "assets/img/pawn/slim-fit/royal-blue/model-4.jpg",
      "assets/img/pawn/slim-fit/royal-blue/plain-1.jpg",
      "assets/img/pawn/slim-fit/royal-blue/plain-2.jpg"
    ],
    "page": "pawn-slim-fit.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-slim-fit-sky-blue",
    "name": "Sky Blue Slim Fit",
    "tag": "Slim Fit",
    "category": "Pawn · Kids",
    "price": 129,
    "image": "assets/img/pawn/slim-fit/sky-blue/model-1.jpg",
    "images": [
      "assets/img/pawn/slim-fit/sky-blue/model-1.jpg",
      "assets/img/pawn/slim-fit/sky-blue/model-2.jpg",
      "assets/img/pawn/slim-fit/sky-blue/model-3.jpg",
      "assets/img/pawn/slim-fit/sky-blue/model-4.jpg",
      "assets/img/pawn/slim-fit/sky-blue/plain-1.jpg",
      "assets/img/pawn/slim-fit/sky-blue/plain-2.jpg"
    ],
    "page": "pawn-slim-fit.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-slim-fit-indigo-blue",
    "name": "Indigo Blue Slim Fit",
    "tag": "Slim Fit",
    "category": "Pawn · Kids",
    "price": 129,
    "image": "assets/img/pawn/slim-fit/indigo-blue/model-1.jpg",
    "images": [
      "assets/img/pawn/slim-fit/indigo-blue/model-1.jpg",
      "assets/img/pawn/slim-fit/indigo-blue/model-2.jpg",
      "assets/img/pawn/slim-fit/indigo-blue/model-3.jpg",
      "assets/img/pawn/slim-fit/indigo-blue/model-4.jpg",
      "assets/img/pawn/slim-fit/indigo-blue/plain-1.jpg",
      "assets/img/pawn/slim-fit/indigo-blue/plain-2.jpg"
    ],
    "page": "pawn-slim-fit.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-slim-fit-hunter-green",
    "name": "Hunter Green Slim Fit",
    "tag": "Slim Fit",
    "category": "Pawn · Kids",
    "price": 129,
    "image": "assets/img/pawn/slim-fit/hunter-green/model-1.jpg",
    "images": [
      "assets/img/pawn/slim-fit/hunter-green/model-1.jpg",
      "assets/img/pawn/slim-fit/hunter-green/model-2.jpg",
      "assets/img/pawn/slim-fit/hunter-green/model-3.jpg",
      "assets/img/pawn/slim-fit/hunter-green/model-4.jpg",
      "assets/img/pawn/slim-fit/hunter-green/plain-1.jpg",
      "assets/img/pawn/slim-fit/hunter-green/plain-2.jpg"
    ],
    "page": "pawn-slim-fit.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-slim-fit-burgundy",
    "name": "Burgundy Slim Fit",
    "tag": "Slim Fit",
    "category": "Pawn · Kids",
    "price": 129,
    "image": "assets/img/pawn/slim-fit/burgundy/model-1.jpg",
    "images": [
      "assets/img/pawn/slim-fit/burgundy/model-1.jpg",
      "assets/img/pawn/slim-fit/burgundy/model-2.jpg",
      "assets/img/pawn/slim-fit/burgundy/model-3.jpg",
      "assets/img/pawn/slim-fit/burgundy/model-4.jpg",
      "assets/img/pawn/slim-fit/burgundy/plain-1.jpg",
      "assets/img/pawn/slim-fit/burgundy/plain-2.jpg"
    ],
    "page": "pawn-slim-fit.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-suit-vest-set-black",
    "name": "Black Suit Vest Set",
    "tag": "Suit Vest Set",
    "category": "Pawn · Kids",
    "price": 89,
    "image": "assets/img/pawn/suit-vest-set/black/model-1.jpg",
    "images": [
      "assets/img/pawn/suit-vest-set/black/model-1.jpg",
      "assets/img/pawn/suit-vest-set/black/model-2.jpg",
      "assets/img/pawn/suit-vest-set/black/model-3.jpg",
      "assets/img/pawn/suit-vest-set/black/model-4.jpg",
      "assets/img/pawn/suit-vest-set/black/plain-1.jpg",
      "assets/img/pawn/suit-vest-set/black/plain-2.jpg"
    ],
    "page": "pawn-suit-vest-set.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-suit-vest-set-indigo",
    "name": "Indigo Suit Vest Set",
    "tag": "Suit Vest Set",
    "category": "Pawn · Kids",
    "price": 89,
    "image": "assets/img/pawn/suit-vest-set/indigo/model-1.jpg",
    "images": [
      "assets/img/pawn/suit-vest-set/indigo/model-1.jpg",
      "assets/img/pawn/suit-vest-set/indigo/model-2.jpg",
      "assets/img/pawn/suit-vest-set/indigo/model-3.jpg",
      "assets/img/pawn/suit-vest-set/indigo/model-4.jpg",
      "assets/img/pawn/suit-vest-set/indigo/plain-1.jpg",
      "assets/img/pawn/suit-vest-set/indigo/plain-2.jpg"
    ],
    "page": "pawn-suit-vest-set.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-suit-vest-set-light-gray",
    "name": "Light Gray Suit Vest Set",
    "tag": "Suit Vest Set",
    "category": "Pawn · Kids",
    "price": 89,
    "image": "assets/img/pawn/suit-vest-set/light-gray/model-1.jpg",
    "images": [
      "assets/img/pawn/suit-vest-set/light-gray/model-1.jpg",
      "assets/img/pawn/suit-vest-set/light-gray/model-2.jpg",
      "assets/img/pawn/suit-vest-set/light-gray/model-3.jpg",
      "assets/img/pawn/suit-vest-set/light-gray/model-4.jpg",
      "assets/img/pawn/suit-vest-set/light-gray/plain-1.jpg",
      "assets/img/pawn/suit-vest-set/light-gray/plain-2.jpg"
    ],
    "page": "pawn-suit-vest-set.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-suit-vest-set-navy",
    "name": "Navy Suit Vest Set",
    "tag": "Suit Vest Set",
    "category": "Pawn · Kids",
    "price": 89,
    "image": "assets/img/pawn/suit-vest-set/navy/model-1.jpg",
    "images": [
      "assets/img/pawn/suit-vest-set/navy/model-1.jpg",
      "assets/img/pawn/suit-vest-set/navy/model-2.jpg",
      "assets/img/pawn/suit-vest-set/navy/model-3.jpg",
      "assets/img/pawn/suit-vest-set/navy/model-4.jpg",
      "assets/img/pawn/suit-vest-set/navy/plain-1.jpg",
      "assets/img/pawn/suit-vest-set/navy/plain-2.jpg"
    ],
    "page": "pawn-suit-vest-set.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-tuxedo-full-black",
    "name": "Full Black Tuxedo",
    "tag": "Tuxedo",
    "category": "Pawn · Kids",
    "price": 139,
    "image": "assets/img/pawn/tuxedo/full-black/model-1.jpg",
    "images": [
      "assets/img/pawn/tuxedo/full-black/model-1.jpg",
      "assets/img/pawn/tuxedo/full-black/model-2.jpg",
      "assets/img/pawn/tuxedo/full-black/model-3.jpg",
      "assets/img/pawn/tuxedo/full-black/model-4.jpg",
      "assets/img/pawn/tuxedo/full-black/plain-1.jpg",
      "assets/img/pawn/tuxedo/full-black/plain-2.jpg"
    ],
    "page": "pawn-tuxedo.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-tuxedo-white-black",
    "name": "White & Black Tuxedo",
    "tag": "Tuxedo",
    "category": "Pawn · Kids",
    "price": 139,
    "image": "assets/img/pawn/tuxedo/white-black/model-1.jpg",
    "images": [
      "assets/img/pawn/tuxedo/white-black/model-1.jpg",
      "assets/img/pawn/tuxedo/white-black/model-2.jpg",
      "assets/img/pawn/tuxedo/white-black/model-3.jpg",
      "assets/img/pawn/tuxedo/white-black/model-4.jpg",
      "assets/img/pawn/tuxedo/white-black/plain-1.jpg",
      "assets/img/pawn/tuxedo/white-black/plain-2.jpg"
    ],
    "page": "pawn-tuxedo.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-tuxedo-full-white",
    "name": "Full White Tuxedo",
    "tag": "Tuxedo",
    "category": "Pawn · Kids",
    "price": 139,
    "image": "assets/img/pawn/tuxedo/full-white/model-1.jpg",
    "images": [
      "assets/img/pawn/tuxedo/full-white/model-1.jpg",
      "assets/img/pawn/tuxedo/full-white/model-2.jpg",
      "assets/img/pawn/tuxedo/full-white/model-3.jpg",
      "assets/img/pawn/tuxedo/full-white/model-4.jpg",
      "assets/img/pawn/tuxedo/full-white/plain-1.jpg",
      "assets/img/pawn/tuxedo/full-white/plain-2.jpg"
    ],
    "page": "pawn-tuxedo.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-tuxedo-charcoal",
    "name": "Charcoal Tuxedo",
    "tag": "Tuxedo",
    "category": "Pawn · Kids",
    "price": 139,
    "image": "assets/img/pawn/tuxedo/charcoal/model-1.jpg",
    "images": [
      "assets/img/pawn/tuxedo/charcoal/model-1.jpg",
      "assets/img/pawn/tuxedo/charcoal/model-2.jpg",
      "assets/img/pawn/tuxedo/charcoal/model-3.jpg",
      "assets/img/pawn/tuxedo/charcoal/model-4.jpg",
      "assets/img/pawn/tuxedo/charcoal/plain-1.jpg",
      "assets/img/pawn/tuxedo/charcoal/plain-2.jpg"
    ],
    "page": "pawn-tuxedo.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-tuxedo-shiny-charcoal",
    "name": "Shiny Charcoal Tuxedo",
    "tag": "Tuxedo",
    "category": "Pawn · Kids",
    "price": 139,
    "image": "assets/img/pawn/tuxedo/shiny-charcoal/model-1.jpg",
    "images": [
      "assets/img/pawn/tuxedo/shiny-charcoal/model-1.jpg",
      "assets/img/pawn/tuxedo/shiny-charcoal/model-2.jpg",
      "assets/img/pawn/tuxedo/shiny-charcoal/model-3.jpg",
      "assets/img/pawn/tuxedo/shiny-charcoal/model-4.jpg",
      "assets/img/pawn/tuxedo/shiny-charcoal/plain-1.jpg"
    ],
    "page": "pawn-tuxedo.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-tuxedo-gray",
    "name": "Gray Tuxedo",
    "tag": "Tuxedo",
    "category": "Pawn · Kids",
    "price": 139,
    "image": "assets/img/pawn/tuxedo/gray/model-1.jpg",
    "images": [
      "assets/img/pawn/tuxedo/gray/model-1.jpg",
      "assets/img/pawn/tuxedo/gray/model-2.jpg",
      "assets/img/pawn/tuxedo/gray/model-3.jpg",
      "assets/img/pawn/tuxedo/gray/model-4.jpg",
      "assets/img/pawn/tuxedo/gray/plain-1.jpg",
      "assets/img/pawn/tuxedo/gray/plain-2.jpg"
    ],
    "page": "pawn-tuxedo.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-tuxedo-navy",
    "name": "Navy Tuxedo",
    "tag": "Tuxedo",
    "category": "Pawn · Kids",
    "price": 139,
    "image": "assets/img/pawn/tuxedo/navy/model-1.jpg",
    "images": [
      "assets/img/pawn/tuxedo/navy/model-1.jpg",
      "assets/img/pawn/tuxedo/navy/model-2.jpg",
      "assets/img/pawn/tuxedo/navy/model-3.jpg",
      "assets/img/pawn/tuxedo/navy/model-4.jpg",
      "assets/img/pawn/tuxedo/navy/plain-1.jpg",
      "assets/img/pawn/tuxedo/navy/plain-2.jpg"
    ],
    "page": "pawn-tuxedo.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-tuxedo-royal-blue",
    "name": "Royal Blue Tuxedo",
    "tag": "Tuxedo",
    "category": "Pawn · Kids",
    "price": 139,
    "image": "assets/img/pawn/tuxedo/royal-blue/model-1.jpg",
    "images": [
      "assets/img/pawn/tuxedo/royal-blue/model-1.jpg",
      "assets/img/pawn/tuxedo/royal-blue/model-2.jpg",
      "assets/img/pawn/tuxedo/royal-blue/model-3.jpg",
      "assets/img/pawn/tuxedo/royal-blue/model-4.jpg",
      "assets/img/pawn/tuxedo/royal-blue/plain-1.jpg",
      "assets/img/pawn/tuxedo/royal-blue/plain-2.jpg"
    ],
    "page": "pawn-tuxedo.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-tuxedo-red",
    "name": "Red Tuxedo",
    "tag": "Tuxedo",
    "category": "Pawn · Kids",
    "price": 139,
    "image": "assets/img/pawn/tuxedo/red/model-1.jpg",
    "images": [
      "assets/img/pawn/tuxedo/red/model-1.jpg",
      "assets/img/pawn/tuxedo/red/model-2.jpg",
      "assets/img/pawn/tuxedo/red/model-3.jpg",
      "assets/img/pawn/tuxedo/red/model-4.jpg",
      "assets/img/pawn/tuxedo/red/plain-1.jpg",
      "assets/img/pawn/tuxedo/red/plain-2.jpg"
    ],
    "page": "pawn-tuxedo.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-tuxedo-burgundy",
    "name": "Burgundy Tuxedo",
    "tag": "Tuxedo",
    "category": "Pawn · Kids",
    "price": 139,
    "image": "assets/img/pawn/tuxedo/burgundy/model-1.jpg",
    "images": [
      "assets/img/pawn/tuxedo/burgundy/model-1.jpg",
      "assets/img/pawn/tuxedo/burgundy/model-2.jpg",
      "assets/img/pawn/tuxedo/burgundy/model-3.jpg",
      "assets/img/pawn/tuxedo/burgundy/model-4.jpg",
      "assets/img/pawn/tuxedo/burgundy/plain-1.jpg",
      "assets/img/pawn/tuxedo/burgundy/plain-2.jpg"
    ],
    "page": "pawn-tuxedo.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-tuxedo-hunter-green",
    "name": "Hunter Green Tuxedo",
    "tag": "Tuxedo",
    "category": "Pawn · Kids",
    "price": 139,
    "image": "assets/img/pawn/tuxedo/hunter-green/model-1.jpg",
    "images": [
      "assets/img/pawn/tuxedo/hunter-green/model-1.jpg",
      "assets/img/pawn/tuxedo/hunter-green/model-2.jpg",
      "assets/img/pawn/tuxedo/hunter-green/model-3.jpg",
      "assets/img/pawn/tuxedo/hunter-green/model-4.jpg",
      "assets/img/pawn/tuxedo/hunter-green/plain-1.jpg",
      "assets/img/pawn/tuxedo/hunter-green/plain-2.jpg"
    ],
    "page": "pawn-tuxedo.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-tuxedo-khaki",
    "name": "Khaki Tuxedo",
    "tag": "Tuxedo",
    "category": "Pawn · Kids",
    "price": 139,
    "image": "assets/img/pawn/tuxedo/khaki/model-1.jpg",
    "images": [
      "assets/img/pawn/tuxedo/khaki/model-1.jpg",
      "assets/img/pawn/tuxedo/khaki/model-2.jpg",
      "assets/img/pawn/tuxedo/khaki/model-3.jpg",
      "assets/img/pawn/tuxedo/khaki/model-4.jpg",
      "assets/img/pawn/tuxedo/khaki/plain-1.jpg"
    ],
    "page": "pawn-tuxedo.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-tuxedo-vest-set-black",
    "name": "Black Tuxedo Vest Set",
    "tag": "Tuxedo Vest Set",
    "category": "Pawn · Kids",
    "price": 99,
    "image": "assets/img/pawn/tuxedo-vest-set/black/model-1.jpg",
    "images": [
      "assets/img/pawn/tuxedo-vest-set/black/model-1.jpg",
      "assets/img/pawn/tuxedo-vest-set/black/model-2.jpg",
      "assets/img/pawn/tuxedo-vest-set/black/model-3.jpg",
      "assets/img/pawn/tuxedo-vest-set/black/model-4.jpg",
      "assets/img/pawn/tuxedo-vest-set/black/plain-1.jpg",
      "assets/img/pawn/tuxedo-vest-set/black/plain-2.jpg"
    ],
    "page": "pawn-tuxedo-vest-set.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-tuxedo-vest-set-burgundy",
    "name": "Burgundy Tuxedo Vest Set",
    "tag": "Tuxedo Vest Set",
    "category": "Pawn · Kids",
    "price": 99,
    "image": "assets/img/pawn/tuxedo-vest-set/burgundy/model-1.jpg",
    "images": [
      "assets/img/pawn/tuxedo-vest-set/burgundy/model-1.jpg",
      "assets/img/pawn/tuxedo-vest-set/burgundy/model-2.jpg",
      "assets/img/pawn/tuxedo-vest-set/burgundy/model-3.jpg",
      "assets/img/pawn/tuxedo-vest-set/burgundy/model-4.jpg",
      "assets/img/pawn/tuxedo-vest-set/burgundy/plain-1.jpg",
      "assets/img/pawn/tuxedo-vest-set/burgundy/plain-2.jpg"
    ],
    "page": "pawn-tuxedo-vest-set.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-tuxedo-vest-set-light-gray",
    "name": "Light Gray Tuxedo Vest Set",
    "tag": "Tuxedo Vest Set",
    "category": "Pawn · Kids",
    "price": 99,
    "image": "assets/img/pawn/tuxedo-vest-set/light-gray/model-1.jpg",
    "images": [
      "assets/img/pawn/tuxedo-vest-set/light-gray/model-1.jpg",
      "assets/img/pawn/tuxedo-vest-set/light-gray/model-2.jpg",
      "assets/img/pawn/tuxedo-vest-set/light-gray/model-3.jpg",
      "assets/img/pawn/tuxedo-vest-set/light-gray/model-4.jpg",
      "assets/img/pawn/tuxedo-vest-set/light-gray/plain-1.jpg",
      "assets/img/pawn/tuxedo-vest-set/light-gray/plain-2.jpg"
    ],
    "page": "pawn-tuxedo-vest-set.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "pawn-tuxedo-vest-set-light-navy",
    "name": "Light Navy Tuxedo Vest Set",
    "tag": "Tuxedo Vest Set",
    "category": "Pawn · Kids",
    "price": 99,
    "image": "assets/img/pawn/tuxedo-vest-set/light-navy/model-1.jpg",
    "images": [
      "assets/img/pawn/tuxedo-vest-set/light-navy/model-1.jpg",
      "assets/img/pawn/tuxedo-vest-set/light-navy/model-2.jpg",
      "assets/img/pawn/tuxedo-vest-set/light-navy/model-3.jpg",
      "assets/img/pawn/tuxedo-vest-set/light-navy/model-4.jpg",
      "assets/img/pawn/tuxedo-vest-set/light-navy/plain-1.jpg",
      "assets/img/pawn/tuxedo-vest-set/light-navy/plain-2.jpg"
    ],
    "page": "pawn-tuxedo-vest-set.html",
    "sizes": [
      "2T",
      "3T",
      "4",
      "5",
      "6",
      "7",
      "8",
      "10",
      "12",
      "14"
    ],
    "description": "Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment."
  },
  {
    "id": "bishop-bowtie",
    "name": "The Pin",
    "tag": "Black bow tie",
    "price": 85,
    "image": "assets/img/diagram/bowtie.png",
    "page": "bishop.html",
    "category": "Bishop · Accessories",
    "sizes": [
      "One size"
    ],
    "description": "A finishing touch for the complete Checkmatela look. Concept imagery illustrates the planned collection; final materials and details are to be confirmed.",
    "concept": true
  },
  {
    "id": "bishop-pocketsquare",
    "name": "The Fianchetto",
    "tag": "White pocket square",
    "price": 65,
    "image": "assets/img/diagram/pocketsquare.png",
    "page": "bishop.html",
    "category": "Bishop · Accessories",
    "sizes": [
      "One size"
    ],
    "description": "A finishing touch for the complete Checkmatela look. Concept imagery illustrates the planned collection; final materials and details are to be confirmed.",
    "concept": true
  },
  {
    "id": "bishop-cufflinks",
    "name": "The Zugzwang",
    "tag": "Gold & onyx cufflinks",
    "price": 120,
    "image": "assets/img/diagram/cufflinks.png",
    "page": "bishop.html",
    "category": "Bishop · Accessories",
    "sizes": [
      "One size"
    ],
    "description": "A finishing touch for the complete Checkmatela look. Concept imagery illustrates the planned collection; final materials and details are to be confirmed.",
    "concept": true
  },
  {
    "id": "rook-shoes",
    "name": "The Castle",
    "tag": "Black Oxford shoes",
    "price": 295,
    "image": "assets/img/diagram/shoes.png",
    "page": "rook.html",
    "category": "Rook · Shoes",
    "sizes": [
      "US 7",
      "US 8",
      "US 9",
      "US 10",
      "US 11",
      "US 12",
      "US 13"
    ],
    "description": "A finishing touch for the complete Checkmatela look. Concept imagery illustrates the planned collection; final materials and details are to be confirmed.",
    "concept": true
  }
];
