/* Site menu + search (every page).
   - Hamburger (.McButton, in the sticky header) opens a two-level menu: The Board (5 departments) → that department's links, a
     "Build your look" customizer that deep-links into the King / Pawn filters (js/shop.js reads ?color=&occasion=&style=&max=), and help links.
   - The search icon opens a site-wide search; the menu has its own search bar. Both read js/search-index.js (generated by tools/gen_nav.py).
   Nothing is sent anywhere — it all runs in the browser. */
(() => {
  "use strict";
  const $ = (s, r = document) => r.querySelector(s), $$ = (s, r = document) => [...r.querySelectorAll(s)];
  const esc = s => String(s).replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
  const money = n => "$" + Number(n).toLocaleString("en-US");
  const header = $("#siteHeader"), btn = $(".McButton");
  if (!header || !btn) return;
  const desktop = window.matchMedia("(min-width: 981px)");
  const reduce = window.matchMedia("(prefers-reduced-motion: reduce)").matches;

  const GLYPHS = '<symbol id="mg-king" viewBox="0 0 100 130"> <path fill="currentColor" d="M47 4 H53 V13 H62 V19 H53 V28 H47 V19 H38 V13 H47 Z"/> <circle fill="currentColor" cx="50" cy="35" r="6.5"/> <path fill="currentColor" d="M37 43 C37 37 63 37 63 43 C66 49 65 55 60 59 C67 63 69 69 67 75 L33 75 C31 69 33 63 40 59 C35 55 34 49 37 43 Z"/> <path fill="currentColor" d="M42 75 H58 L64 100 H36 Z"/> <path fill="currentColor" d="M28 100 H72 L69 108 H31 Z"/> <path fill="currentColor" d="M22 108 H78 L74 128 H26 Z"/> </symbol><symbol id="mg-queen" viewBox="0 0 100 130"> <circle fill="currentColor" cx="50" cy="12" r="5"/> <path fill="currentColor" d="M31 38 L35 20 L42 32 L50 16 L58 32 L65 20 L69 38 Z"/> <path fill="currentColor" d="M35 40 C35 34 65 34 65 40 C68 46 67 52 61 56 C68 60 70 66 68 72 L32 72 C30 66 32 60 39 56 C33 52 32 46 35 40 Z"/> <path fill="currentColor" d="M41 72 H59 L64 100 H36 Z"/> <path fill="currentColor" d="M28 100 H72 L69 108 H31 Z"/> <path fill="currentColor" d="M22 108 H78 L74 128 H26 Z"/> </symbol><symbol id="mg-rook" viewBox="0 0 100 130"> <path fill="currentColor" d="M30 20 H39 V28 H46 V20 H54 V28 H61 V20 H70 V44 H61 L58 56 H42 L39 44 H30 Z"/> <path fill="currentColor" d="M40 56 H60 L65 100 H35 Z"/> <path fill="currentColor" d="M28 100 H72 L69 108 H31 Z"/> <path fill="currentColor" d="M22 108 H78 L74 128 H26 Z"/> </symbol><symbol id="mg-bishop" viewBox="0 0 100 130"> <circle fill="currentColor" cx="50" cy="12" r="4.5"/> <path fill="currentColor" d="M50 20 C37 30 33 46 44 56 C35 62 30 68 30 74 L70 74 C70 68 65 62 56 56 C67 46 63 30 50 20 Z"/> <path fill="currentColor" d="M40 37 L60 43 L58 47 L38 41 Z"/> <path fill="currentColor" d="M41 74 H59 L64 100 H36 Z"/> <path fill="currentColor" d="M28 100 H72 L69 108 H31 Z"/> <path fill="currentColor" d="M22 108 H78 L74 128 H26 Z"/> </symbol><symbol id="mg-pawn" viewBox="0 0 100 130"> <circle fill="currentColor" cx="50" cy="30" r="13"/> <path fill="currentColor" d="M39 46 C39 40 61 40 61 46 L55 60 H45 Z"/> <path fill="currentColor" d="M43 60 H57 L64 100 H36 Z"/> <path fill="currentColor" d="M28 100 H72 L69 108 H31 Z"/> <path fill="currentColor" d="M22 108 H78 L74 128 H26 Z"/> </symbol>';
  const SWATCH = { black: "#17191b", navy: "#1f2d4a", blue: "#2f5fa8", grey: "#8b8f95", cream: "#e9dcc3", burgundy: "#6d1f2f", white: "#f6f3ec", red: "#b3202e", green: "#2d5a45", neutral: "#c8b79b" };
  const PAWN = [["Slim Fit", "pawn-slim-fit.html"], ["Suit Vest Set", "pawn-suit-vest-set.html"], ["Tuxedo", "pawn-tuxedo.html"], ["Tuxedo Vest Set", "pawn-tuxedo-vest-set.html"]];

  const DEPTS = [
    { key: "king", n: "01", name: "King", who: "Men", href: "king.html", img: "assets/img/categories/men-model.webp", glyph: "king",
      blurb: "Suits, three-pieces and tuxedos from $179 — for weddings, black tie and the boardroom.",
      links: [["All suits & tuxedos", "king.html"], ["Tuxedos", "king.html?style=Tuxedo"], ["Three-piece suits", "king.html?style=Three-piece"], ["Two-piece suits", "king.html?style=Two-piece"], ["Wedding looks", "king.html?occasion=Wedding"], ["Business looks", "king.html?occasion=Business"], ["Groomsmen: save up to 15%", "king.html?occasion=Wedding", "Deal"]] },
    { key: "queen", n: "02", name: "Queen", who: "Women", href: "queen.html", img: "assets/img/categories/queen-model.webp", glyph: "queen",
      blurb: "The women's collection is on its way. Tell us what you're dressing for and we'll plan around it.",
      links: [["Women's collection", "queen.html", "Soon"], ["Ask about fit & timing", "book-a-fitting.html"], ["Size guide", "size-guide.html"]] },
    { key: "pawn", n: "03", name: "Pawn", who: "Kids", href: "pawn.html", img: "assets/img/categories/kids-model.webp", glyph: "pawn",
      blurb: "Boys' suits, vest sets and tuxedos from $115 — the same fit-and-finish, sized for growing up.",
      links: [["All kids' styles", "pawn.html"], ...PAWN.map(([l, u]) => [l, u]), ["Kids' size guide", "size-guide.html"]] },
    { key: "bishop", n: "04", name: "Bishop", who: "Accessories", href: "bishop.html", img: "assets/img/categories/accessories-flatlay.webp", glyph: "bishop", list: "Bishop",
      blurb: "Bow ties, pocket squares and cufflinks that finish the look.", links: [["All accessories", "bishop.html"]] },
    { key: "rook", n: "05", name: "Rook", who: "Shoes", href: "rook.html", img: "assets/img/categories/rook-model.webp", glyph: "rook", list: "Rook",
      blurb: "Oxfords, loafers and boots polished for the occasion.", links: [["All shoes", "rook.html"]] },
  ];
  const QUICK = [["Wedding", "king.html?occasion=Wedding"], ["Black tie", "king.html?occasion=Black%20tie"], ["Prom", "king.html?occasion=Prom"], ["Business", "king.html?occasion=Business"], ["Kids", "pawn.html"]];
  const HELP = [["Find your look", "find-your-look.html"], ["Size guide", "size-guide.html"], ["Alterations", "alterations.html"], ["Shipping & returns", "shipping-returns.html"], ["Our story", "our-story.html"], ["Master tailors", "master-tailors.html"], ["Sustainability", "sustainability.html"], ["Press", "press.html"]];
  const OCC = ["Wedding", "Black tie", "Prom", "Business", "Formal", "Summer"], COL = ["Black", "Navy", "Blue", "Grey", "Cream", "Burgundy"], STY = ["Tuxedo", "Three-piece", "Two-piece"];
  const BUDGET = [["Any price", ""], ["Under $200", "199"], ["Under $225", "224"], ["Up to $250", "250"]];
  const WHO = [["men", "Men", "king.html"], ["kids", "Kids", "pawn.html"], ["women", "Women", "queen.html", "Soon"], ["acc", "Accessories", "bishop.html"], ["shoes", "Shoes", "rook.html"]];
  const ARROW = '<svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6"/></svg>';
  const GLASS = '<svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="M21 21l-4.3-4.3"/></svg>';

  /* ---------------------------------------------------------------- search index (lazy) */
  let IDX = null, recs = [], idxWaiters = [];
  function withIndex(cb) {
    if (IDX) return cb();
    idxWaiters.push(cb);
    if (withIndex.loading) return; withIndex.loading = true;
    const s = document.createElement("script"); s.src = "js/search-index.js?v=1";
    s.onload = () => { IDX = window.CHECKMATELA_INDEX; prep(); idxWaiters.splice(0).forEach(f => f()); };
    document.head.appendChild(s);
  }
  const norm = s => String(s).toLowerCase().replace(/[’']/g, "").replace(/[^a-z0-9$%+ ]+/g, " ").replace(/\s+/g, " ").trim();
  const SYN = { tux: "tuxedo", tuxedos: "tuxedo", suits: "suit", boys: "kids", boy: "kids", kid: "kids", child: "kids", children: "kids", shoes: "shoe", ties: "tie", bowtie: "bow tie", bowties: "bow tie",
    groomsman: "groomsmen", refund: "returns", refunds: "returns", return: "returns", exchange: "exchanges", sizing: "size", sizes: "size", cufflink: "cufflinks", alteration: "alterations",
    tailor: "tailors", dress: "dresses", gown: "dresses", gowns: "dresses", womens: "women", mens: "men", discounts: "discount", coupon: "promo", delivery: "shipping" };
  const KIND_WORDS = { King: "men mens suit", Pawn: "kids boys suit", Bishop: "accessories", Rook: "shoes shoe" };
  function prep() {
    recs = [];
    IDX.products.forEach(p => recs.push({ type: "product", title: p.t, sub: p.s, url: p.u, price: p.p, img: p.i, kind: p.k, f: p.f || {}, hay: norm([p.t, p.s, p.k, KIND_WORDS[p.k], Object.values(p.f || {}).join(" ").replace(/\|/g, " ")].join(" ")) }));
    IDX.pages.forEach(p => recs.push({ type: "page", title: p.t, sub: p.s, url: p.u, hay: norm(p.t + " " + p.s + " " + p.kw) }));
    IDX.help.forEach(p => recs.push({ type: "help", title: p.t, sub: p.s, url: p.u, hay: norm(p.t + " " + p.s + " " + p.kw) }));
    recs.forEach(r => { r.tn = norm(r.title); r.tw = r.tn.split(" "); r.hw = r.hay.split(" "); });
  }
  const tokens = q => norm(q).split(" ").filter(Boolean).flatMap(t => (SYN[t] || t).split(" "));
  function search(q) {
    const toks = tokens(q); if (!toks.length) return [];
    const phrase = norm(q), out = [];
    for (const r of recs) {
      let sc = 0;
      for (const t of toks) {
        if (r.tw.some(w => w.startsWith(t))) sc += 4; else if (r.tn.includes(t)) sc += 3; else if (r.hw.some(w => w.startsWith(t))) sc += 2; else if (r.hay.includes(t)) sc += 1; else { sc = -1; break; }
      }
      if (sc < 0) continue;
      if (r.tn.includes(phrase)) sc += 3;
      if (r.type === "help") sc += 1;
      out.push([sc, r]);
    }
    return out.sort((a, b) => b[0] - a[0]).map(x => x[1]);
  }
  const mark = (text, q) => {
    const toks = [...new Set(tokens(q))].filter(t => t.length > 1).sort((a, b) => b.length - a.length);
    let s = esc(text); toks.forEach(t => { s = s.replace(new RegExp("(" + t.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + ")", "ig"), "<mark>$1</mark>"); }); return s;
  };
  function resultsHTML(q) {
    const hits = search(q), prods = hits.filter(r => r.type === "product"), more = hits.filter(r => r.type !== "product");
    if (!hits.length) return `<div class="sr-empty"><p>No matches for “<b>${esc(q)}</b>”.</p><p>Try <button type="button" data-q="tuxedo">tuxedo</button>, <button type="button" data-q="navy">navy</button>, <button type="button" data-q="returns">returns</button> or <a href="book-a-fitting.html">ask us directly ${ARROW}</a></p></div>`;
    const item = r => r.type === "product"
      ? `<a class="sr-item" href="${r.url}"><img src="${esc(r.img)}" alt="" loading="lazy" width="56" height="64"><span class="sr-txt"><b>${mark(r.title, q)}</b><i>${esc(r.sub)}</i></span><span class="sr-price">${money(r.price)}</span></a>`
      : `<a class="sr-item sr-item--page" href="${r.url}"><span class="sr-ic">${ARROW}</span><span class="sr-txt"><b>${mark(r.title, q)}</b><i>${esc(r.sub)}</i></span></a>`;
    let h = "";
    if (prods.length) h += `<h4 class="sr-h">Pieces <em>${prods.length}</em></h4><div class="sr-list">${prods.slice(0, 6).map(item).join("")}</div>${prods.length > 6 ? `<p class="sr-more">Showing 6 of ${prods.length} — add a word to narrow it down.</p>` : ""}`;
    if (more.length) h += `<h4 class="sr-h">Pages &amp; help</h4><div class="sr-list">${more.slice(0, 6).map(item).join("")}</div>`;
    return h;
  }
  const POPULAR = ["Tuxedo", "Navy suit", "Groomsmen discount", "Boys suit", "Bow tie", "Returns", "Size guide", "Alterations"];

  /* wires an <input> to a results element; returns helpers */
  function bindSearch(input, results, { onState = () => {}, popular = null } = {}) {
    const run = () => {
      const q = input.value.trim();
      if (!q) { results.innerHTML = popular ? popular() : ""; onState(false); return; }
      withIndex(() => { results.innerHTML = resultsHTML(q); onState(true); setActive(results, 0, false); });
      onState(true);
    };
    input.addEventListener("input", run);
    input.addEventListener("focus", () => withIndex(() => {}));
    input.addEventListener("keydown", e => {
      const links = $$("a.sr-item", results);
      if (e.key === "ArrowDown" || e.key === "ArrowUp") {
        if (!links.length) return; e.preventDefault();
        const cur = links.findIndex(l => l.classList.contains("is-active")), n = (cur + (e.key === "ArrowDown" ? 1 : -1) + links.length) % links.length;
        setActive(results, n, true);
      } else if (e.key === "Enter") {
        const a = $("a.sr-item.is-active", results) || links[0];
        if (a) { e.preventDefault(); location.href = a.getAttribute("href"); }
      }
    });
    results.addEventListener("click", e => { const b = e.target.closest("[data-q]"); if (b) { input.value = b.dataset.q; run(); input.focus(); } });
    return { run };
  }
  function setActive(results, n, scroll) {
    const links = $$("a.sr-item", results); links.forEach((l, i) => l.classList.toggle("is-active", i === n));
    if (scroll && links[n]) links[n].scrollIntoView({ block: "nearest" });
  }
  const popularHTML = () => `<div class="sr-pop"><h4 class="sr-h">Popular searches</h4><div class="sr-chips">${POPULAR.map(p => `<button type="button" data-q="${esc(p)}">${esc(p)}</button>`).join("")}</div>
    <h4 class="sr-h">Browse by piece</h4><div class="sr-chips">${DEPTS.map(d => `<a href="${d.href}">${d.name} <i>${d.who}</i></a>`).join("")}</div></div>`;

  /* ---------------------------------------------------------------- menu DOM */
  const glyphSvg = g => `<svg class="board-glyph" viewBox="0 0 100 130" aria-hidden="true"><use href="#mg-${g}"/></svg>`;
  function deptHTML(d) {
    const list = d.list && IDX ? IDX.products.filter(p => p.k === d.list) : [];
    const links = d.links.map(([l, u, tag]) => `<li><a href="${u}">${esc(l)}${tag ? `<em class="tag tag--${tag === "Deal" ? "deal" : "soon"}">${tag}</em>` : ""}</a></li>`).join("");
    const mini = list.length ? `<ul class="dept__mini">${list.map(p => `<li><a href="${p.u}"><img src="${esc(p.i)}" alt="" loading="lazy" width="44" height="50"><span><b>${esc(p.t)}</b><i>${esc(p.s)}</i></span><span class="dept__price">${money(p.p)}</span></a></li>`).join("")}</ul>` : "";
    return `<div class="dept" data-dept="${d.key}"><p class="dept__eyebrow">${d.who}</p><h3 class="dept__title">${d.name}</h3><p class="dept__blurb">${esc(d.blurb)}</p>
      <ul class="dept__links">${links}</ul>${mini}
      <a class="dept__tile" href="${d.href}"><img src="${d.img}" alt="" loading="lazy"><span><b>Shop ${d.name}</b><i>${d.who}</i>${ARROW}</span></a></div>`;
  }
  const chip = (g, v, label, pressed, extra = "") => `<button type="button" class="chip" data-g="${g}" data-v="${esc(v)}" aria-pressed="${pressed}"${extra}>${esc(label)}</button>`;

  const menu = document.createElement("div");
  menu.className = "menu"; menu.id = "siteMenu"; menu.setAttribute("role", "dialog"); menu.setAttribute("aria-modal", "true"); menu.setAttribute("aria-label", "Site menu"); menu.hidden = true; menu.tabIndex = -1;
  const scrim = document.createElement("div"); scrim.className = "menu-scrim"; scrim.hidden = true;
  menu.innerHTML = `<svg width="0" height="0" style="position:absolute" aria-hidden="true"><defs>${GLYPHS}</defs></svg>
    <div class="menu__checks" aria-hidden="true"></div>
    <div class="menu__scroll">
      <div class="menu__top">
        <form class="menu-search" role="search" action="#" onsubmit="return false">${GLASS}<input type="search" placeholder="Search suits, sizes, returns…" aria-label="Search the site" autocomplete="off" enterkeyhint="search"><kbd aria-hidden="true">/</kbd></form>
        <div class="menu-quick"><span>Shop by occasion</span>${QUICK.map(([l, u]) => `<a href="${u}">${l}</a>`).join("")}</div>
      </div>
      <div class="menu__results" hidden aria-live="polite"></div>
      <div class="menu__body">
        <section class="menu__board" aria-label="The Board — shop by department">
          <h2 class="menu-eyebrow">The Board</h2>
          <ol class="board">${DEPTS.map((d, i) => `<li class="board-item" data-dept="${d.key}" style="--i:${i}">
            <a class="board-row" href="${d.href}" aria-expanded="false"><span class="board-n">${d.n}</span>${glyphSvg(d.glyph)}<span class="board-t"><b>${d.name}</b><i>${d.who}</i></span><span class="board-arrow">${ARROW}</span></a>
            <div class="board-acc"></div></li>`).join("")}</ol>
        </section>
        <section class="menu__dept" aria-live="polite"></section>
        <aside class="menu__build" aria-label="Build your look">
          <div class="build__head"><span class="menu-eyebrow menu-eyebrow--dark">Build your look</span><button type="button" class="build__reset">Reset</button></div>
          <p class="build__lede">Tell us what you need and jump straight to the pieces that fit.</p>
          <div class="build__grp"><span class="build__lab" id="bl-who">I'm shopping for</span><div class="chips" role="group" aria-labelledby="bl-who">${WHO.map(([k, l, , tag]) => chip("who", k, l + (tag ? " · soon" : ""), k === "men")).join("")}</div></div>
          <div class="build__opts" data-for="men">
            <div class="build__grp"><span class="build__lab" id="bl-occ">Occasion</span><div class="chips" role="group" aria-labelledby="bl-occ">${OCC.map(o => chip("occasion", o, o, false)).join("")}</div></div>
            <div class="build__grp"><span class="build__lab" id="bl-col">Colour</span><div class="chips chips--sw" role="group" aria-labelledby="bl-col">${COL.map(c => `<button type="button" class="sw" data-g="color" data-v="${c}" aria-pressed="false" aria-label="${c}" title="${c}" style="--c:${SWATCH[c.toLowerCase()]}"><i></i><span>${c}</span></button>`).join("")}</div></div>
            <div class="build__grp"><span class="build__lab" id="bl-sty">Style</span><div class="chips" role="group" aria-labelledby="bl-sty">${STY.map(o => chip("style", o, o, false)).join("")}</div></div>
            <div class="build__grp"><span class="build__lab" id="bl-bud">Budget</span><div class="chips" role="group" aria-labelledby="bl-bud">${BUDGET.map(([l, v], i) => chip("max", v, l, i === 0)).join("")}</div></div>
          </div>
          <div class="build__opts" data-for="kids" hidden>
            <div class="build__grp"><span class="build__lab" id="bl-cut">Cut</span><div class="chips" role="group" aria-labelledby="bl-cut">${PAWN.map(([l, u]) => chip("cut", u, l, false)).join("")}</div></div>
            <div class="build__grp"><span class="build__lab" id="bl-kc">Colour</span><div class="chips chips--sw" role="group" aria-labelledby="bl-kc" data-kidcolors></div></div>
          </div>
          <div class="build__opts build__note" data-for="women" hidden><p>Women's formal wear is coming. <a href="book-a-fitting.html">Tell us what you're dressing for</a> and we'll plan around it.</p></div>
          <a class="build__go" href="king.html"><span class="build__go-t">Show looks</span>${ARROW}</a>
          <p class="build__fine">Prices are previews; checkout isn't connected. Filters open on the shop page.</p>
        </aside>
      </div>
      <div class="menu__foot">
        <div class="foot-help"><b>Need a hand?</b><a class="foot-cta" href="book-a-fitting.html">Ask about fit</a><a class="foot-tel" href="tel:+13108906991">+1 (310) 890-6991</a></div>
        <ul class="foot-links">${HELP.map(([l, u]) => `<li><a href="${u}">${l}</a></li>`).join("")}</ul>
      </div>
    </div>`;
  header.after(menu); menu.after(scrim);

  const mScroll = $(".menu__scroll", menu), mBody = $(".menu__body", menu), mResults = $(".menu__results", menu), deptCol = $(".menu__dept", menu);
  let activeDept = "king";
  function renderDeptAll() {
    $$(".board-item", menu).forEach(li => { $(".board-acc", li).innerHTML = deptHTML(DEPTS.find(d => d.key === li.dataset.dept)); });
    showDept(activeDept);
  }
  function showDept(key) {
    activeDept = key;
    $$(".board-item", menu).forEach(li => li.classList.toggle("is-current", li.dataset.dept === key));
    deptCol.innerHTML = deptHTML(DEPTS.find(d => d.key === key));
    deptCol.dataset.dept = key;
    if (!reduce) { const el = deptCol.firstElementChild; el.classList.remove("dept--in"); void el.offsetWidth; el.classList.add("dept--in"); }
  }
  renderDeptAll();
  $$(".board-item", menu).forEach(li => {
    const row = $(".board-row", li);
    li.addEventListener("mouseenter", () => { if (desktop.matches) showDept(li.dataset.dept); });
    row.addEventListener("focus", () => { if (desktop.matches) showDept(li.dataset.dept); });
    row.addEventListener("click", e => {
      if (desktop.matches) return;                                  // desktop: the row is a normal link
      e.preventDefault();
      const open = !li.classList.contains("is-expanded");
      $$(".board-item", menu).forEach(o => { o.classList.remove("is-expanded"); $(".board-row", o).setAttribute("aria-expanded", "false"); });
      if (open) { li.classList.add("is-expanded"); row.setAttribute("aria-expanded", "true"); setTimeout(() => li.scrollIntoView({ block: "nearest", behavior: reduce ? "auto" : "smooth" }), 60); }
    });
  });

  /* ---------------------------------------------------------------- Build your look */
  const B = { who: "men", occasion: new Set(), color: new Set(), style: new Set(), max: "", cut: "", kcolor: new Set() };
  const build = $(".menu__build", menu), go = $(".build__go", build);
  function matchMen() {
    return IDX ? IDX.products.filter(p => p.k === "King" && (!B.occasion.size || (p.f.occasion || "").split("|").some(v => B.occasion.has(v))) && (!B.color.size || B.color.has(p.f.color)) && (!B.style.size || B.style.has(p.f.style)) && (!B.max || p.p <= +B.max)).length : null;
  }
  function matchKids() {
    return IDX ? IDX.products.filter(p => p.k === "Pawn" && (!B.cut || p.u === B.cut) && (!B.kcolor.size || B.kcolor.has(p.f.color))).length : null;
  }
  function renderBuild() {
    $$("[data-for]", build).forEach(el => el.hidden = el.dataset.for !== B.who);
    $$(".chip, .sw", build).forEach(c => {
      const g = c.dataset.g, v = c.dataset.v;
      const on = g === "who" ? B.who === v : g === "max" ? B.max === v : g === "cut" ? B.cut === v : g === "color" ? B.color.has(v) : g === "kcolor" ? B.kcolor.has(v) : B[g].has(v);
      c.setAttribute("aria-pressed", on);
    });
    if (B.who === "kids" && IDX) {
      const cols = [...new Set(IDX.products.filter(p => p.k === "Pawn" && (!B.cut || p.u === B.cut)).map(p => p.f.color))].sort();
      B.kcolor.forEach(c => { if (!cols.includes(c)) B.kcolor.delete(c); });
      $("[data-kidcolors]", build).innerHTML = cols.map(c => `<button type="button" class="sw" data-g="kcolor" data-v="${c}" aria-pressed="${B.kcolor.has(c)}" aria-label="${c}" title="${c}" style="--c:${SWATCH[c.toLowerCase()] || "#c9c9c9"}"><i></i><span>${c}</span></button>`).join("");
    }
    let href, label, n;
    const q = (k, set) => set.size ? `${k}=${[...set].map(encodeURIComponent).join(",")}` : "";
    if (B.who === "men") { href = "king.html"; const qs = [q("occasion", B.occasion), q("color", B.color), q("style", B.style), B.max ? "max=" + B.max : ""].filter(Boolean).join("&"); if (qs) href += "?" + qs; n = matchMen(); label = n === null ? "Show looks" : n ? `Show ${n} look${n === 1 ? "" : "s"}` : "No exact match — see all"; if (n === 0) href = "king.html"; }
    else if (B.who === "kids") { href = B.cut || "pawn.html"; const qs = B.cut ? q("color", B.kcolor) : ""; if (qs) href += "?" + qs; n = matchKids(); label = !B.cut ? "See all kids' styles" : n === null ? "Show looks" : `Show ${n} look${n === 1 ? "" : "s"}`; }
    else if (B.who === "women") { href = "queen.html"; label = "Visit Queen"; }
    else { const w = WHO.find(x => x[0] === B.who); href = w[2]; label = B.who === "acc" ? "Shop accessories" : "Shop shoes"; }
    go.href = href; $(".build__go-t", go).textContent = label;
  }
  build.addEventListener("click", e => {
    const c = e.target.closest(".chip, .sw"); if (c) {
      const g = c.dataset.g, v = c.dataset.v;
      if (g === "who") B.who = v; else if (g === "max") B.max = v; else if (g === "cut") B.cut = B.cut === v ? "" : v;
      else { const s = g === "kcolor" ? B.kcolor : B[g]; s.has(v) ? s.delete(v) : s.add(v); }
      renderBuild(); return;
    }
    if (e.target.closest(".build__reset")) { B.who = "men"; B.occasion.clear(); B.color.clear(); B.style.clear(); B.kcolor.clear(); B.max = ""; B.cut = ""; renderBuild(); }
  });
  go.addEventListener("click", () => closeMenu(true));
  renderBuild();

  /* ---------------------------------------------------------------- menu open / close */
  let open = false, lastFocus = null;
  const place = () => { const r = header.getBoundingClientRect(); const t = Math.max(0, Math.round(r.bottom)); menu.style.setProperty("--menu-top", t + "px"); scrim.style.top = t + "px"; };
  function openMenu() {
    if (open) return; closeSearch(true); open = true; lastFocus = document.activeElement; place();
    menu.hidden = false; scrim.hidden = false; document.body.classList.add("nav-open");
    withIndex(() => { renderDeptAll(); renderBuild(); });
    void menu.offsetWidth; setTimeout(() => { if (open) { menu.classList.add("is-open"); scrim.classList.add("is-on"); } }, 30);
    btn.classList.add("is-open"); btn.setAttribute("aria-expanded", "true"); btn.setAttribute("aria-label", "Close menu");
    $(".hdr-menu-label", header) && ($(".hdr-menu-label", header).textContent = "Close");
    mScroll.scrollTop = 0; setTimeout(() => menu.focus({ preventScroll: true }), 30);
  }
  function closeMenu(keepFocus) {
    if (!open) return; open = false;
    menu.classList.remove("is-open"); scrim.classList.remove("is-on"); btn.classList.remove("is-open"); btn.setAttribute("aria-expanded", "false"); btn.setAttribute("aria-label", "Open menu");
    $(".hdr-menu-label", header) && ($(".hdr-menu-label", header).textContent = "Menu");
    document.body.classList.remove("nav-open");
    setTimeout(() => { if (!open) { menu.hidden = true; scrim.hidden = true; clearMenuSearch(); } }, reduce ? 0 : 420);
    if (!keepFocus && lastFocus && lastFocus.focus) lastFocus.focus();
  }
  const toggleMenu = () => open ? closeMenu() : openMenu();
  const menuToggle = e => { e.preventDefault(); toggleMenu(); };
  btn.addEventListener("click", menuToggle);
  btn.addEventListener("keydown", e => { if (e.key === "Enter" || e.key === " ") menuToggle(e); });
  const lbl = $(".hdr-menu-label", header); if (lbl) lbl.addEventListener("click", menuToggle);
  scrim.addEventListener("click", () => closeMenu());
  menu.addEventListener("click", e => { const a = e.target.closest("a[href]"); if (a && !a.matches(".board-row") && !a.closest(".build__go")) closeMenu(true); if (a && a.matches(".board-row") && desktop.matches) closeMenu(true); });
  window.addEventListener("resize", () => { if (open) place(); });
  window.addEventListener("scroll", () => { if (open) place(); }, { passive: true });
  window.addEventListener("pageshow", e => { if (e.persisted) { closeMenu(true); closeSearch(true); } });

  const menuInput = $(".menu-search input", menu);
  function clearMenuSearch() { menuInput.value = ""; mResults.hidden = true; mBody.hidden = false; mResults.innerHTML = ""; }
  bindSearch(menuInput, mResults, { onState: on => { mResults.hidden = !on; mBody.hidden = on; $(".menu__foot", menu).hidden = on; } });
  menuInput.addEventListener("input", () => { if (!menuInput.value.trim()) { $(".menu__foot", menu).hidden = false; } });

  /* ---------------------------------------------------------------- search overlay */
  const searchEl = document.createElement("div");
  searchEl.className = "search"; searchEl.id = "siteSearch"; searchEl.hidden = true; searchEl.setAttribute("role", "dialog"); searchEl.setAttribute("aria-modal", "true"); searchEl.setAttribute("aria-label", "Search");
  searchEl.innerHTML = `<div class="search__scrim"></div><div class="search__sheet">
    <form class="search__form" role="search" action="#" onsubmit="return false">${GLASS}<input type="search" placeholder="Search suits, sizes, returns…" aria-label="Search the site" autocomplete="off" enterkeyhint="search"><button type="button" class="search__x" aria-label="Close search"><span>Esc</span></button></form>
    <div class="search__res" aria-live="polite"></div></div>`;
  document.body.appendChild(searchEl);
  const sInput = $("input", searchEl), sRes = $(".search__res", searchEl);
  bindSearch(sInput, sRes, { popular: popularHTML });
  let sOpen = false, sLast = null;
  function openSearch() {
    if (sOpen) return; closeMenu(true); sOpen = true; sLast = document.activeElement;
    searchEl.hidden = false; document.body.classList.add("search-open");
    sRes.innerHTML = popularHTML(); withIndex(() => {});
    void searchEl.offsetWidth; setTimeout(() => { if (sOpen) { searchEl.classList.add("is-open"); sInput.focus(); } }, 30);
  }
  function closeSearch(keepFocus) {
    if (!sOpen) return; sOpen = false; searchEl.classList.remove("is-open"); document.body.classList.remove("search-open");
    setTimeout(() => { if (!sOpen) { searchEl.hidden = true; sInput.value = ""; } }, reduce ? 0 : 320);
    if (!keepFocus && sLast && sLast.focus) sLast.focus();
  }
  $(".search__scrim", searchEl).addEventListener("click", () => closeSearch());
  $(".search__x", searchEl).addEventListener("click", () => closeSearch());
  searchEl.addEventListener("click", e => { if (e.target.closest("a[href]")) closeSearch(true); });
  $$('button[aria-label="Search"]').forEach(b => b.addEventListener("click", openSearch));
  $$("[data-open-search]").forEach(b => b.addEventListener("click", openSearch));

  /* ---------------------------------------------------------------- keyboard */
  document.addEventListener("keydown", e => {
    const typing = /^(INPUT|TEXTAREA|SELECT)$/.test((document.activeElement || {}).tagName) || (document.activeElement || {}).isContentEditable;
    if (e.key === "Escape") { if (sOpen) { closeSearch(); e.preventDefault(); } else if (open) { if (menuInput.value) { clearMenuSearch(); $(".menu__foot", menu).hidden = false; menuInput.blur(); } else closeMenu(); e.preventDefault(); } return; }
    if (((e.key === "/" && !typing) || ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === "k")) && !e.altKey) { e.preventDefault(); if (open) menuInput.focus(); else openSearch(); return; }
    if (e.key === "Tab" && (open || sOpen)) {
      const root = sOpen ? searchEl : menu, list = [...(open ? [btn] : []), ...$$('a[href], button:not([disabled]), input:not([disabled])', root)].filter(el => el.offsetParent !== null || el === btn);
      if (!list.length) return; const first = list[0], last = list[list.length - 1];
      if (e.shiftKey && (document.activeElement === first || document.activeElement === root)) { e.preventDefault(); last.focus(); }
      else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); }
    }
  });

  /* warm the index shortly after load so the first search is instant */
  const warm = () => withIndex(() => {});
  if ("requestIdleCallback" in window) requestIdleCallback(warm, { timeout: 3000 }); else setTimeout(warm, 1500);
})();
