/* Site navigation + search (every page).
   Desktop (≥1240px): category links across the header (static HTML in each page); hovering one opens a full-width panel with columns of
   links, colour swatches and image tiles (content: MEGA below). Phones/tablets: the McButton hamburger opens a simple accordion with the same links.
   Search: header icon, "/" or Ctrl/Cmd+K, or the bar inside the mobile menu — client-side over js/search-index.js (generated by tools/gen_nav.py).
   Colour / style / occasion links deep-link into the King and Pawn filters (js/shop.js reads ?color=&occasion=&style=&max=). Nothing is sent anywhere. */
(() => {
  "use strict";
  const $ = (s, r = document) => r.querySelector(s), $$ = (s, r = document) => [...r.querySelectorAll(s)];
  const esc = s => String(s).replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
  const money = n => "$" + Number(n).toLocaleString("en-US");
  const header = $("#siteHeader"), btn = $(".McButton");
  if (!header) return;
  const wide = window.matchMedia("(min-width: 1240px)");
  const reduce = window.matchMedia("(prefers-reduced-motion: reduce)").matches;

  const HEX = { black: "#17191b", navy: "#1f2d4a", blue: "#2f5fa8", grey: "#8b8f95", cream: "#e9dcc3", burgundy: "#6d1f2f", white: "#f6f3ec", red: "#b3202e", green: "#2d5a45", neutral: "#c8b79b", charcoal: "#3b3f45", brown: "#6b4a33", beige: "#d8c7a3", silver: "#b9bcc2", gold: "#c9a24a", teal: "#2e5560", pink: "#e6a9b8", purple: "#5d3a7a" };
  const ARROW = '<svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6"/></svg>';
  const GLASS = '<svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="M21 21l-4.3-4.3"/></svg>';
  const sw = (names, base) => names.map(n => [n, `${base}${encodeURIComponent(n)}`, HEX[n.toLowerCase()] || "#c9c9c9"]);

  /* ---------------------------------------------------------------- what each category panel shows */
  const MEGA = {
    king: { label: "Men", sub: "King", href: "king.html",
      cols: [
        { h: "Featured", links: [["Shop all men", "king.html"], ["Two-piece suits", "king.html?style=Two-piece"], ["Three-piece suits", "king.html?style=Three-piece"], ["Tuxedos", "king.html?style=Tuxedo"], ["Dress pants", "king.html?style=Pants"], ["Jackets", "king.html?style=Jacket"], ["Groomsmen: save up to 15%", "king.html?occasion=Wedding", "Deal"]] },
        { h: "Brands", brands: true, wide: true, links: [["Antonio Uomo", "antonio-uomo.html"]] },
        { h: "Color", sw: sw(["Black", "Charcoal", "Grey", "Navy", "Blue", "Burgundy", "Brown", "Beige"], "king.html?color=") },
        { h: "Occasion", links: ["Wedding", "Black tie", "Prom", "Business", "Formal", "Summer"].map(o => [o, "king.html?occasion=" + encodeURIComponent(o)]) },
      ],
      tiles: [
        { img: "assets/img/categories/men-model.webp", t: "Wedding season", p: "Suits and tuxedos for the whole party. 10% off at 3+, 15% at 6+.", a: "Shop weddings", href: "king.html?occasion=Wedding" },
        { img: "assets/img/products/sicilian-onyx-tux.jpg", t: "Black tie, sorted", p: "Classic black, navy and charcoal tuxedos, ready for the night.", a: "Shop black tie", href: "king.html?occasion=Black%20tie" },
      ],
      help: "Not sure what to wear?", helpLink: ["Find your look", "find-your-look.html"] },
    queen: { label: "Women", sub: "Queen", href: "queen.html",
      cols: [
        { h: "Featured", links: [["Women's collection", "queen.html", "Soon"], ["Ask about timing", "book-a-fitting.html"], ["Size guide", "size-guide.html"]] },
        { h: "Plan your look", links: [["Find your look", "find-your-look.html"], ["Ask about fit", "book-a-fitting.html"], ["Alterations", "alterations.html"], ["Shipping & returns", "shipping-returns.html"]] },
      ],
      tiles: [
        { img: "assets/img/categories/queen-model.webp", t: "The Queen collection", p: "Women's formal wear is on its way. Tell us what you're dressing for.", a: "Visit Queen", href: "queen.html" },
        { note: true, t: "Be first to know", p: "Dressing for a wedding or gala? Ask us about timing and we'll plan around your date.", a: "Ask about timing", href: "book-a-fitting.html" },
      ],
      help: "Planning ahead?", helpLink: ["Ask about timing", "book-a-fitting.html"] },
    pawn: { label: "Kids", sub: "Pawn", href: "pawn.html",
      cols: [
        { h: "Featured", links: [["All kids' styles", "pawn.html"], ["Husky fit", "pawn-husky.html"], ["Dress pants", "pawn-pants.html"], ["Compare the cuts", "pawn.html"], ["Kids' size guide", "size-guide.html"], ["Ask about fit", "book-a-fitting.html"], ["Free exchanges", "shipping-returns.html", "Free"]] },
        { h: "Brands", brands: true, wide: true, links: [["Magen Kids", "magen-kids.html"]] },
        { h: "Color", kidsColors: true },
      ],
      tiles: [
        { img: "assets/img/categories/kids-model.webp", t: "Little groomsmen", p: "Suits, tuxedos, vest sets and dress pants, sized 2T to 16, for ring bearers and page boys.", a: "Shop kids", href: "pawn.html" },
        { img: "assets/img/pawn/husky-suit/navy/model-1.jpg", t: "Husky fit", p: "Suits, tuxedos and dress pants cut roomier for larger sizes.", a: "Shop husky fit", href: "pawn-husky.html" },
      ],
      help: "Need help with sizing?", helpLink: ["Kids' size guide", "size-guide.html"] },
    bishop: { label: "Accessories", sub: "Bishop", href: "bishop.html",
      cols: [
        { h: "Featured", links: [["All accessories", "bishop.html"], ["Free with 3+ suits", "king.html?occasion=Wedding", "Deal"], ["Shop weddings", "king.html?occasion=Wedding"]] },
        { h: "Bow ties", pick: ["Bishop", /bow tie/i], fallback: ["All bow ties", "bishop.html"] },
        { h: "Pocket squares", pick: ["Bishop", /pocket square/i], fallback: ["All pocket squares", "bishop.html"] },
        { h: "Cufflinks", pick: ["Bishop", /cufflink/i], fallback: ["All cufflinks", "bishop.html"] },
      ],
      tiles: [
        { img: "assets/img/categories/accessories-flatlay.webp", t: "Finish the look", p: "Silk bow ties, pocket squares and cufflinks from $65.", a: "Shop accessories", href: "bishop.html" },
        { note: true, t: "A gift for the group", p: "Order 3 or more suits together and the organizer gets a free bow tie or pocket square.", a: "See the groomsmen deal", href: "king.html?occasion=Wedding" },
      ],
      help: "Matching a suit?", helpLink: ["Find your look", "find-your-look.html"] },
    rook: { label: "Shoes", sub: "Rook", href: "rook.html",
      cols: [
        { h: "Featured", links: [["All shoes", "rook.html"], ["Size guide", "size-guide.html"], ["Free exchanges", "shipping-returns.html", "Free"]] },
        { h: "Oxfords & derbys", pick: ["Rook", /oxford|derby/i], fallback: ["All oxfords & derbys", "rook.html"] },
        { h: "Loafers & slippers", pick: ["Rook", /loafer|slipper|monk/i], fallback: ["All loafers", "rook.html"] },
        { h: "Boots", pick: ["Rook", /boot/i], fallback: ["All boots", "rook.html"] },
      ],
      tiles: [
        { img: "assets/img/categories/rook-model.webp", t: "Polished for the occasion", p: "Calfskin oxfords, patent loafers and velvet slippers from $220.", a: "Shop shoes", href: "rook.html" },
        { note: true, t: "Trying shoes on?", p: "Wear them indoors only: unmarked soles and the original box keep returns simple.", a: "Read the return policy", href: "shipping-returns.html" },
      ],
      help: "Questions about fit?", helpLink: ["Ask about fit", "book-a-fitting.html"] },
    discover: { label: "Discover", sub: "Help, inspiration & company", href: "find-your-look.html",
      cols: [
        { h: "Help", links: [["Find your look", "find-your-look.html"], ["Ask about fit", "book-a-fitting.html"], ["Size guide", "size-guide.html"], ["Alterations", "alterations.html"], ["Shipping & returns", "shipping-returns.html"], ["FAQ", "faq.html"]] },
        { h: "Inspiration", links: [["Style guide", "blog.html"], ["Lookbook", "lookbook.html"], ["Reviews", "reviews.html"]] },
        { h: "Plan an event", links: [["Weddings & groomsmen", "king.html?occasion=Wedding"], ["Prom", "king.html?occasion=Prom"], ["Black tie", "king.html?occasion=Black%20tie"], ["Business", "king.html?occasion=Business"], ["Kids' formal wear", "pawn.html"]] },
        { h: "Company", links: [["Our story", "our-story.html"], ["Master tailors", "master-tailors.html"], ["Sustainability", "sustainability.html"], ["Press", "press.html"]] },
        { h: "Contact", links: [["+1 (310) 890-6991", "tel:+13108906991"], ["suit.shop.dtla@gmail.com", "mailto:suit.shop.dtla@gmail.com"], ["Los Angeles studio", "book-a-fitting.html"]] },
      ],
      tiles: [],
      help: "Not sure where to begin?", helpLink: ["Find your look", "find-your-look.html"] },
  };
  const MOBILE_ORDER = ["king", "queen", "pawn", "bishop", "rook", "discover"];

  /* ---------------------------------------------------------------- search index (lazy) */
  let IDX = null, recs = [], idxWaiters = [];
  function withIndex(cb) {
    if (IDX) return cb();
    idxWaiters.push(cb);
    if (withIndex.loading) return; withIndex.loading = true;
    const s = document.createElement("script"); s.src = "js/search-index.js?v=0309b062";
    s.onload = () => { IDX = window.CHECKMATELA_INDEX; prep(); idxWaiters.splice(0).forEach(f => f()); };
    document.head.appendChild(s);
  }
  const norm = s => String(s).toLowerCase().replace(/[’']/g, "").replace(/[^a-z0-9$%+ ]+/g, " ").replace(/\s+/g, " ").trim();
  const SYN = { tux: "tuxedo", tuxedos: "tuxedo", suits: "suit", boys: "kids", boy: "kids", kid: "kids", child: "kids", children: "kids", shoes: "shoe", ties: "tie", bowtie: "bow tie", bowties: "bow tie",
    groomsman: "groomsmen", refund: "returns", refunds: "returns", return: "returns", exchange: "exchanges", sizing: "size", sizes: "size", cufflink: "cufflinks", alteration: "alterations",
    tailor: "tailors", dress: "dresses", gown: "dresses", gowns: "dresses", womens: "women", mens: "men", discounts: "discount", coupon: "promo", delivery: "shipping" };
  const KIND_WORDS = { King: "men mens suit", Pawn: "kids boys suit", Bishop: "accessories", Rook: "shoes shoe" };
  function prep() {
    recs = [];
    IDX.products.forEach(p => recs.push({ type: "product", title: p.t, sub: p.s, url: p.u, price: p.p, img: p.i, kind: p.k, f: p.f || {}, hay: norm([p.t, p.s, p.k, KIND_WORDS[p.k], p.d, Object.values(p.f || {}).join(" ").replace(/\|/g, " ")].join(" ")) }));
    IDX.pages.forEach(p => recs.push({ type: "page", title: p.t, sub: p.s, url: p.u, hay: norm(p.t + " " + p.s + " " + p.kw) }));
    IDX.help.forEach(p => recs.push({ type: "help", title: p.t, sub: p.s, url: p.u, hay: norm(p.t + " " + p.s + " " + p.kw) }));
    recs.forEach(r => { r.tn = norm(r.title); r.tw = r.tn.split(" "); r.hw = r.hay.split(" "); });
  }
  const tokens = q => norm(q).split(" ").filter(Boolean).flatMap(t => (SYN[t] || t).split(" "));
  function search(q) {
    const toks = tokens(q); if (!toks.length) return [];
    const phrase = norm(q), out = [];
    for (const r of recs) {
      let sc = 0;
      for (const t of toks) {
        if (r.tw.some(w => w.startsWith(t))) sc += 4; else if (r.tn.includes(t)) sc += 3; else if (r.hw.some(w => w.startsWith(t))) sc += 2; else if (r.hay.includes(t)) sc += 1; else { sc = -1; break; }
      }
      if (sc < 0) continue;
      if (r.tn.includes(phrase)) sc += 3;
      if (r.type === "help") sc += 1;
      out.push([sc, r]);
    }
    return out.sort((a, b) => b[0] - a[0]).map(x => x[1]);
  }
  const mark = (text, q) => {
    const toks = [...new Set(tokens(q))].filter(t => t.length > 1).sort((a, b) => b.length - a.length);
    let s = esc(text); toks.forEach(t => { s = s.replace(new RegExp("(" + t.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + ")", "ig"), "<mark>$1</mark>"); }); return s;
  };
  function resultsHTML(q) {
    const hits = search(q), prods = hits.filter(r => r.type === "product"), more = hits.filter(r => r.type !== "product");
    if (!hits.length) return `<div class="sr-empty"><p>No matches for “<b>${esc(q)}</b>”.</p><p>Try <button type="button" data-q="tuxedo">tuxedo</button>, <button type="button" data-q="navy">navy</button>, <button type="button" data-q="returns">returns</button> or <a href="book-a-fitting.html">ask us directly ${ARROW}</a></p></div>`;
    const item = r => r.type === "product"
      ? `<a class="sr-item" href="${r.url}"><img src="${esc(r.img)}" alt="" loading="lazy" width="56" height="64"><span class="sr-txt"><b>${mark(r.title, q)}</b><i>${esc(r.sub)}</i></span><span class="sr-price">${money(r.price)}</span></a>`
      : `<a class="sr-item sr-item--page" href="${r.url}"><span class="sr-ic">${ARROW}</span><span class="sr-txt"><b>${mark(r.title, q)}</b><i>${esc(r.sub)}</i></span></a>`;
    let h = "";
    if (prods.length) h += `<h4 class="sr-h">Pieces <em>${prods.length}</em></h4><div class="sr-list">${prods.slice(0, 6).map(item).join("")}</div>${prods.length > 6 ? `<p class="sr-more">Showing 6 of ${prods.length} — add a word to narrow it down.</p>` : ""}`;
    if (more.length) h += `<h4 class="sr-h">Pages &amp; help</h4><div class="sr-list">${more.slice(0, 6).map(item).join("")}</div>`;
    return h;
  }
  /* wires an <input> to a results element; returns helpers */
  function bindSearch(input, results, { onState = () => {}, popular = null } = {}) {
    const run = () => {
      const q = input.value.trim();
      if (!q) { results.innerHTML = popular ? popular() : ""; onState(false); return; }
      withIndex(() => { results.innerHTML = resultsHTML(q); onState(true); setActive(results, 0, false); });
      onState(true);
    };
    input.addEventListener("input", run);
    input.addEventListener("focus", () => withIndex(() => {}));
    input.addEventListener("keydown", e => {
      const links = $$("a.sr-item", results);
      if (e.key === "ArrowDown" || e.key === "ArrowUp") {
        if (!links.length) return; e.preventDefault();
        const cur = links.findIndex(l => l.classList.contains("is-active")), n = (cur + (e.key === "ArrowDown" ? 1 : -1) + links.length) % links.length;
        setActive(results, n, true);
      } else if (e.key === "Enter") {
        const a = $("a.sr-item.is-active", results) || links[0];
        if (a) { e.preventDefault(); location.href = a.getAttribute("href"); }
      }
    });
    results.addEventListener("click", e => { const b = e.target.closest("[data-q]"); if (b) { input.value = b.dataset.q; run(); input.focus(); } });
    return { run };
  }
  function setActive(results, n, scroll) {
    const links = $$("a.sr-item", results); links.forEach((l, i) => l.classList.toggle("is-active", i === n));
    if (scroll && links[n]) links[n].scrollIntoView({ block: "nearest" });
  }
  const POPULAR = ["Tuxedo", "Navy suit", "Groomsmen discount", "Boys suit", "Bow tie", "Returns", "Size guide", "Alterations"];
  const BROWSE = [["Men", "king.html"], ["Women", "queen.html"], ["Kids", "pawn.html"], ["Accessories", "bishop.html"], ["Shoes", "rook.html"]];
  const popularHTML = () => `<div class="sr-pop"><h4 class="sr-h">Popular searches</h4><div class="sr-chips">${POPULAR.map(p => `<button type="button" data-q="${esc(p)}">${esc(p)}</button>`).join("")}</div>
    <h4 class="sr-h">Browse</h4><div class="sr-chips">${BROWSE.map(([l, u]) => `<a href="${u}">${l}</a>`).join("")}</div></div>`;

  /* ---------------------------------------------------------------- panel content */
  const tagHTML = t => t ? `<em class="tag${t === "Deal" ? " tag--deal" : t === "Soon" ? " tag--soon" : ""}">${esc(t)}</em>` : "";
  const swHTML = list => `<ul class="mega__sw">${list.map(([n, href, hex]) => `<li><a href="${href}"><i style="--c:${hex}"></i><span>${esc(n)}</span></a></li>`).join("")}</ul>`;
  const navOf = key => (IDX && IDX.nav || []).find(d => d.key === key);
  const subPages = key => { const n = navOf(key); return n ? n.pages.filter(p => !p.landing) : []; };
  /* a brand (a page with child pages) as a dropdown of its categories; "Shop All" first, same labels as the brand page's category pills */
  const brandDD = (p, open) => `<details class="brand-dd"${open ? " open" : ""}><summary><span>${esc(p.t)}</span><em>${p.n} pieces</em></summary><ul class="mega__list">${p.children.map(c => `<li><a href="${c.u}"><span>${esc(c.t)}</span></a></li>`).join("")}</ul></details>`;
  const flatPages = key => subPages(key).flatMap(p => [{ ...p, depth: 0 }, ...(p.children || []).map(c => ({ ...c, depth: 1 }))]);   // a page, then its child pages
  function kidsColors() {
    if (!IDX) return [];
    const by = {};
    IDX.products.filter(p => p.k === "Pawn").forEach(p => { const c = p.f.color, o = (by[c] = by[c] || {}); o[p.u] = (o[p.u] || 0) + 1; });
    return Object.keys(by).sort().map(c => [c, `${Object.entries(by[c]).sort((a, b) => b[1] - a[1])[0][0]}?color=${encodeURIComponent(c)}`, HEX[c.toLowerCase()] || "#c9c9c9"]);
  }
  function colHTML(c, key) {
    let inner;
    if (c.brands) { const bp = subPages(key).filter(p => p.children); inner = bp.length ? bp.map(p => brandDD(p, false)).join("") : `<ul class="mega__list">${c.links.map(([l, u]) => `<li><a href="${u}"><span>${esc(l)}</span></a></li>`).join("")}</ul>`; }
    else if (c.pages) { const sp = flatPages(key), list = sp.length ? sp.map(p => [p.t, p.u, p.n ? (p.m > p.p ? "from $" : "$") + p.p : "Soon", p.depth]) : c.links; inner = `<ul class="mega__list">${list.map(([l, u, t, dp]) => `<li class="${dp ? "is-child" : ""}"><a href="${u}"><span>${esc(l)}</span>${tagHTML(t)}</a></li>`).join("")}</ul>`; }
    else if (c.sw) inner = swHTML(c.sw);
    else if (c.kidsColors) inner = kidsColors().length ? swHTML(kidsColors()) : `<p class="mega__wait">Loading colours…</p>`;
    else if (c.pick) {
      const items = IDX ? IDX.products.filter(p => p.k === c.pick[0] && c.pick[1].test(p.s)) : [];
      inner = `<ul class="mega__list">${items.length ? items.map(p => `<li><a class="mega__item" href="${p.u}"><img src="${esc(p.i)}" alt="" loading="lazy" width="40" height="46"><span><b>${esc(p.t)}</b><i>${esc(p.s)}</i><em>${money(p.p)}</em></span></a></li>`).join("") : `<li><a href="${c.fallback[1]}">${c.fallback[0]}</a></li>`}</ul>`;
    } else inner = `<ul class="mega__list">${c.links.map(([l, u, t]) => `<li><a href="${u}"><span>${esc(l)}</span>${tagHTML(t)}</a></li>`).join("")}</ul>`;
    return `<div class="mega__col"><h4>${esc(c.h)}</h4>${inner}</div>`;
  }
  const tileHTML = t => t.note
    ? `<a class="mega__tile mega__tile--note" href="${t.href}"><span class="mega__note"><b>${esc(t.t)}</b><span>${esc(t.p)}</span></span><u>${esc(t.a)}</u></a>`
    : `<a class="mega__tile" href="${t.href}"><span class="mega__img"><img src="${t.img}" alt="" loading="lazy"></span><b>${esc(t.t)}</b><span>${esc(t.p)}</span><u>${esc(t.a)}</u></a>`;
  function dynDept(key) {   // a department with no hand-written panel yet: build one from the generated nav data
    const n = navOf(key) || { label: key, sub: key, href: key + ".html", pages: [] };
    return { label: n.label, sub: n.sub, href: n.href, tiles: [], help: "Questions?", helpLink: ["Ask about fit", "book-a-fitting.html"],
      cols: [{ h: "Shop", links: [["Shop all " + n.label.toLowerCase(), n.href], ...n.pages.filter(p => !p.landing).map(p => [p.t, p.u, p.p ? "$" + p.p : ""])] }] };
  }
  const megaHTML = key => {
    const d = MEGA[key] || dynDept(key);
    return `<div class="mega__in${d.tiles.length ? "" : " mega__in--solo"}"><div class="mega__cols" style="--n:${d.cols.length};grid-template-columns:${d.cols.map(c => c.wide ? "1.9fr" : "1fr").join(" ")}">${d.cols.map(c => colHTML(c, key)).join("")}</div><div class="mega__tiles">${d.tiles.map(tileHTML).join("")}</div></div>
      <div class="mega__help">${key === "discover" ? "" : `<b class="mega__brand">${esc(d.sub)} — ${esc(d.label)}</b>`}<span>${esc(d.help)}</span><a href="${d.helpLink[1]}">${esc(d.helpLink[0])}</a>${key === "discover" ? "" : `<a class="mega__all" href="${d.href}">Shop all ${esc(d.label.toLowerCase())} ${ARROW}</a>`}</div>`;
  };

  /* ---------------------------------------------------------------- desktop: hover mega panel */
  const nav = $("#mainNav"), navLinks = nav ? $$("a[data-mega]", nav) : [];
  const mega = document.createElement("div"); mega.className = "mega"; mega.id = "megaPanel"; mega.setAttribute("aria-label", "Category menu"); mega.hidden = true;
  const megaScrim = document.createElement("div"); megaScrim.className = "mega-scrim"; megaScrim.hidden = true;
  header.appendChild(mega); header.after(megaScrim);
  let megaKey = null, megaTimer = 0;
  const here = location.pathname.split("/").pop() || "index.html";
  navLinks.forEach(a => { const k = a.dataset.mega; if (a.getAttribute("href") === here || (k === "pawn" && /^(pawn|magen-kids)/.test(here))) a.setAttribute("aria-current", "page"); a.setAttribute("aria-haspopup", "true"); a.setAttribute("aria-expanded", "false"); a.setAttribute("aria-controls", "megaPanel"); });
  function openMega(key) {
    clearTimeout(megaTimer);
    if (!wide.matches || megaKey === key) return;
    const first = megaKey === null; megaKey = key;
    mega.innerHTML = megaHTML(key); mega.hidden = false; megaScrim.hidden = false;
    megaScrim.style.top = Math.round(header.getBoundingClientRect().bottom) + "px";
    navLinks.forEach(a => { const on = a.dataset.mega === key; a.classList.toggle("is-hover", on); a.setAttribute("aria-expanded", on); });
    if (first) { void mega.offsetWidth; mega.classList.add("is-open"); megaScrim.classList.add("is-on"); }
    if (!reduce) { const el = mega.firstElementChild; el.classList.remove("mega__in--swap"); void el.offsetWidth; el.classList.add("mega__in--swap"); }
    withIndex(() => { if (megaKey === key && (MEGA[key] || dynDept(key)).cols.some(c => c.pick || c.kidsColors || c.pages)) { const sc = mega.scrollTop; mega.innerHTML = megaHTML(key); mega.scrollTop = sc; } });
  }
  function closeMega(now) {
    clearTimeout(megaTimer);
    const run = () => {
      if (megaKey === null) return; megaKey = null;
      mega.classList.remove("is-open"); megaScrim.classList.remove("is-on");
      navLinks.forEach(a => { a.classList.remove("is-hover"); a.setAttribute("aria-expanded", "false"); });
      setTimeout(() => { if (megaKey === null) { mega.hidden = true; megaScrim.hidden = true; } }, reduce ? 0 : 260);
    };
    if (now) run(); else megaTimer = setTimeout(run, 140);
  }
  navLinks.forEach(a => {
    a.addEventListener("mouseenter", () => openMega(a.dataset.mega));
    a.addEventListener("focus", () => openMega(a.dataset.mega));
    a.addEventListener("click", e => { if (e.pointerType === "touch" && wide.matches && megaKey !== a.dataset.mega) { e.preventDefault(); openMega(a.dataset.mega); } });
    a.addEventListener("keydown", e => { if (e.key === "ArrowDown") { e.preventDefault(); openMega(a.dataset.mega); const f = $("a", mega); if (f) f.focus(); } });
  });
  header.addEventListener("mouseenter", () => clearTimeout(megaTimer));
  header.addEventListener("mouseleave", () => closeMega());
  header.addEventListener("focusout", e => { if (!header.contains(e.relatedTarget)) closeMega(); });
  mega.addEventListener("click", e => { if (e.target.closest("a[href]")) closeMega(true); });
  window.addEventListener("scroll", () => { if (megaKey) megaScrim.style.top = Math.round(header.getBoundingClientRect().bottom) + "px"; }, { passive: true });

  /* ---------------------------------------------------------------- phones & tablets: hamburger menu */
  const menu = document.createElement("div");
  menu.className = "menu"; menu.id = "siteMenu"; menu.setAttribute("role", "dialog"); menu.setAttribute("aria-modal", "true"); menu.setAttribute("aria-label", "Site menu"); menu.hidden = true; menu.tabIndex = -1;
  const scrim = document.createElement("div"); scrim.className = "menu-scrim"; scrim.hidden = true;
  const secHTML = c => c.sw ? `<h4>${esc(c.h)}</h4>${swHTML(c.sw)}`
    : c.kidsColors ? (kidsColors().length ? `<h4>${esc(c.h)}</h4>${swHTML(kidsColors())}` : "")
    : c.pick ? `<h4>${esc(c.h)}</h4><ul class="mega__list">${(IDX ? IDX.products.filter(p => p.k === c.pick[0] && c.pick[1].test(p.s)) : []).map(p => `<li><a href="${p.u}"><span>${esc(p.t)} <i>${esc(p.s)}</i></span><em>${money(p.p)}</em></a></li>`).join("") || `<li><a href="${c.fallback[1]}">${c.fallback[0]}</a></li>`}</ul>`
    : `<h4>${esc(c.h)}</h4><ul class="mega__list">${c.links.map(([l, u, t]) => `<li><a href="${u}"><span>${esc(l)}</span>${tagHTML(t)}</a></li>`).join("")}</ul>`;
  const PLUS = '<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M12 5v14M5 12h14"/></svg>';
  /* Inside a category: 1) shop all (counts every product page of the department), 2) its product pages (auto-discovered), 3) browse-by links, 4) highlights */
  function accPanel(k) {
    const m = MEGA[k], n = navOf(k), label = (n && n.label) || (m && m.label) || k, href = (n && n.href) || (m && m.href) || k + ".html";
    let h = `<a class="acc-all" href="${href}"><span>Shop all ${esc(label.toLowerCase())}</span><em>${n ? (n.total ? n.total + (n.total === 1 ? " item" : " items") : "Coming soon") : ""}</em>${ARROW}</a>`;
    const sp = subPages(k), brands = sp.filter(p => p.children), plain = sp.filter(p => !p.children);
    if (brands.length) h += `<div class="acc-sec"><h4>Brands</h4>${brands.map(p => brandDD(p, false)).join("")}</div>`;
    if (plain.length) h += `<div class="acc-sec"><h4>Product pages</h4><ul class="mega__list">${plain.map(p => `<li><a href="${p.u}"><span>${esc(p.t)}</span><em>${p.n ? p.n + (p.n === 1 ? " item" : " items") + (p.p ? " · from " + money(p.p) : "") : "Coming soon"}</em></a></li>`).join("")}</ul></div>`;
    const cols = m ? m.cols : [], feat = cols.find(c => /^featured$/i.test(c.h));
    cols.filter(c => c !== feat && !c.pages && !c.brands).forEach(c => { const x = secHTML(c); if (x) h += `<div class="acc-sec">${x}</div>`; });
    if (feat) h += `<div class="acc-sec">${secHTML({ ...feat, h: "Highlights" })}</div>`;
    return h;
  }
  function accHTML() {
    const keys = [...((IDX && IDX.nav) ? IDX.nav.map(d => d.key) : ["king", "queen", "pawn", "bishop", "rook"]), "discover"];
    return keys.map(k => {
      const m = MEGA[k], n = navOf(k), label = (n && n.label) || (m && m.label) || k, sub = (n && n.sub) || (m && m.sub) || "";
      const body = k === "discover" ? `<a class="acc-all" href="find-your-look.html"><span>Find your look</span>${ARROW}</a>${m.cols.map(c => `<div class="acc-sec">${secHTML(c)}</div>`).join("")}` : accPanel(k);
      return `<li class="acc-item" data-k="${k}"><button type="button" class="acc-row" aria-expanded="false"><span><b>${esc(label)}</b><i>${esc(sub)}</i></span>${PLUS}</button><div class="acc-panel" hidden>${body}</div></li>`;
    }).join("");
  }
  menu.innerHTML = `<div class="menu__scroll">
      <form class="menu-search" role="search" action="#" onsubmit="return false">${GLASS}<input type="search" placeholder="Search suits, sizes, returns…" aria-label="Search the site" autocomplete="off" enterkeyhint="search"></form>
      <div class="menu__results" hidden aria-live="polite"></div>
      <div class="menu__main"><ul class="acc">${accHTML()}</ul>
        <div class="menu__help"><b>Get expert guidance</b><p>Questions about fit, sizing or timing? We're happy to help.</p><div><a class="menu__cta" href="book-a-fitting.html">Ask about fit</a><a href="tel:+13108906991">+1 (310) 890-6991</a></div></div></div>
    </div>`;
  header.after(menu); menu.after(scrim);
  const mScroll = $(".menu__scroll", menu), mMain = $(".menu__main", menu), mResults = $(".menu__results", menu), menuInput = $(".menu-search input", menu);
  menu.addEventListener("click", e => {
    const row = e.target.closest(".acc-row");
    if (row) { const item = row.parentElement, open = row.getAttribute("aria-expanded") !== "true"; $$(".acc-row", menu).forEach(r => { r.setAttribute("aria-expanded", "false"); r.nextElementSibling.hidden = true; }); if (open) { row.setAttribute("aria-expanded", "true"); row.nextElementSibling.hidden = false; setTimeout(() => item.scrollIntoView({ block: "nearest", behavior: reduce ? "auto" : "smooth" }), 40); } return; }
    if (e.target.closest("a[href]")) closeMenu(true);
  });

  let open = false, lastFocus = null;
  const place = () => { const t = Math.max(0, Math.round(header.getBoundingClientRect().bottom)); menu.style.setProperty("--menu-top", t + "px"); scrim.style.top = t + "px"; };
  function openMenu() {
    if (open) return; closeSearch(true); closeMega(true); open = true; lastFocus = document.activeElement; place();
    menu.hidden = false; scrim.hidden = false; document.body.classList.add("nav-open");
    withIndex(() => { const ex = $(".acc-row[aria-expanded=true]", menu); $(".acc", menu).innerHTML = accHTML(); if (ex) { const r = $(`.acc-item[data-k="${ex.parentElement.dataset.k}"] .acc-row`, menu); if (r) { r.setAttribute("aria-expanded", "true"); r.nextElementSibling.hidden = false; } } });
    void menu.offsetWidth; setTimeout(() => { if (open) { menu.classList.add("is-open"); scrim.classList.add("is-on"); } }, 30);
    btn.classList.add("is-open"); btn.setAttribute("aria-expanded", "true"); btn.setAttribute("aria-label", "Close menu");
    const l = $(".hdr-menu-label", header); if (l) l.textContent = "Close";
    mScroll.scrollTop = 0; setTimeout(() => menu.focus({ preventScroll: true }), 30);
  }
  function closeMenu(keepFocus) {
    if (!open) return; open = false;
    menu.classList.remove("is-open"); scrim.classList.remove("is-on"); btn.classList.remove("is-open"); btn.setAttribute("aria-expanded", "false"); btn.setAttribute("aria-label", "Open menu");
    const l = $(".hdr-menu-label", header); if (l) l.textContent = "Menu";
    document.body.classList.remove("nav-open");
    setTimeout(() => { if (!open) { menu.hidden = true; scrim.hidden = true; clearMenuSearch(); } }, reduce ? 0 : 380);
    if (!keepFocus && lastFocus && lastFocus.focus) lastFocus.focus();
  }
  const menuToggle = e => { e.preventDefault(); open ? closeMenu() : openMenu(); };
  if (btn) {
    btn.addEventListener("click", menuToggle);
    btn.addEventListener("keydown", e => { if (e.key === "Enter" || e.key === " ") menuToggle(e); });
    const lbl = $(".hdr-menu-label", header); if (lbl) lbl.addEventListener("click", menuToggle);
  }
  scrim.addEventListener("click", () => closeMenu());
  window.addEventListener("resize", () => { if (open) { if (wide.matches) closeMenu(true); else place(); } if (!wide.matches) closeMega(true); });
  window.addEventListener("scroll", () => { if (open) place(); }, { passive: true });
  window.addEventListener("pageshow", e => { if (e.persisted) { closeMenu(true); closeSearch(true); closeMega(true); } });
  function clearMenuSearch() { menuInput.value = ""; mResults.hidden = true; mMain.hidden = false; mResults.innerHTML = ""; }
  bindSearch(menuInput, mResults, { onState: on => { mResults.hidden = !on; mMain.hidden = on; } });

  /* ---------------------------------------------------------------- search overlay */
  const searchEl = document.createElement("div");
  searchEl.className = "search"; searchEl.id = "siteSearch"; searchEl.hidden = true; searchEl.setAttribute("role", "dialog"); searchEl.setAttribute("aria-modal", "true"); searchEl.setAttribute("aria-label", "Search");
  searchEl.innerHTML = `<div class="search__scrim"></div><div class="search__sheet">
    <form class="search__form" role="search" action="#" onsubmit="return false">${GLASS}<input type="search" placeholder="Search suits, sizes, returns…" aria-label="Search the site" autocomplete="off" enterkeyhint="search"><button type="button" class="search__x" aria-label="Close search"><span>Esc</span></button></form>
    <div class="search__res" aria-live="polite"></div></div>`;
  document.body.appendChild(searchEl);
  const sInput = $("input", searchEl), sRes = $(".search__res", searchEl);
  bindSearch(sInput, sRes, { popular: popularHTML });
  let sOpen = false, sLast = null;
  function openSearch() {
    if (sOpen) return; closeMenu(true); closeMega(true); sOpen = true; sLast = document.activeElement;
    searchEl.hidden = false; document.body.classList.add("search-open");
    sRes.innerHTML = popularHTML(); withIndex(() => {});
    void searchEl.offsetWidth; setTimeout(() => { if (sOpen) { searchEl.classList.add("is-open"); sInput.focus(); } }, 30);
  }
  function closeSearch(keepFocus) {
    if (!sOpen) return; sOpen = false; searchEl.classList.remove("is-open"); document.body.classList.remove("search-open");
    setTimeout(() => { if (!sOpen) { searchEl.hidden = true; sInput.value = ""; } }, reduce ? 0 : 320);
    if (!keepFocus && sLast && sLast.focus) sLast.focus();
  }
  $(".search__scrim", searchEl).addEventListener("click", () => closeSearch());
  $(".search__x", searchEl).addEventListener("click", () => closeSearch());
  searchEl.addEventListener("click", e => { if (e.target.closest("a[href]")) closeSearch(true); });
  $$('button[aria-label="Search"]').forEach(b => b.addEventListener("click", openSearch));

  /* ---------------------------------------------------------------- keyboard */
  document.addEventListener("keydown", e => {
    const typing = /^(INPUT|TEXTAREA|SELECT)$/.test((document.activeElement || {}).tagName) || (document.activeElement || {}).isContentEditable;
    if (e.key === "Escape") { if (sOpen) { closeSearch(); e.preventDefault(); } else if (megaKey) { const k = megaKey; closeMega(true); const a = navLinks.find(x => x.dataset.mega === k); if (a) a.focus(); e.preventDefault(); } else if (open) { if (menuInput.value) { clearMenuSearch(); menuInput.blur(); } else closeMenu(); e.preventDefault(); } return; }
    if (((e.key === "/" && !typing) || ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === "k")) && !e.altKey) { e.preventDefault(); if (open) menuInput.focus(); else openSearch(); return; }
    if (e.key === "Tab" && (open || sOpen)) {
      const root = sOpen ? searchEl : menu, list = [...(open && btn ? [btn] : []), ...$$("a[href], button:not([disabled]), input:not([disabled])", root)].filter(el => el.offsetParent !== null || el === btn);
      if (!list.length) return; const first = list[0], last = list[list.length - 1];
      if (e.shiftKey && (document.activeElement === first || document.activeElement === root)) { e.preventDefault(); last.focus(); }
      else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); }
    }
  });

  /* warm the index shortly after load so search and the panels' product lists are instant */
  const warm = () => withIndex(() => {});
  if ("requestIdleCallback" in window) requestIdleCallback(warm, { timeout: 2500 }); else setTimeout(warm, 1200);
})();
