/* Shop engine — filters, sort, compare and Quick View with reviews for any product grid.

   Everything is driven by data attributes generated by tools/shoplib.py (see its docstring), so adding products or new
   attributes needs no JS changes:
     wrapper  [data-shop] data-facets='[{"key":"color","label":"Colour","swatch":true},…]' data-review-facets='[["height","Height"],…]'
     cards    [data-id][data-name][data-tag][data-price][data-img][data-f-<facet>="A|B"]
   Facets with fewer than two distinct values are hidden. Reviews come from js/reviews-data.js. */
(() => {
  "use strict";
  const SWATCH = {
    black: "#1a1a1c", grey: "#8b8f95", gray: "#8b8f95", navy: "#1f2d4a", blue: "#2f5fa8", cream: "#e9dcc3", burgundy: "#6d1f2f",
    green: "#2d5a45", red: "#b3202e", white: "#f6f3ec", neutral: "#c8b79b", brown: "#6b4a33", pink: "#e6a9b8", purple: "#5d3a7a",
    dark: "#2a2a2c", mid: "#8a8d92", light: "#dcdcd6", tan: "#b89b74", other: "#c9c9c9"
  };
  const $ = (s, r = document) => r.querySelector(s);
  const $$ = (s, r = document) => [...r.querySelectorAll(s)];
  const h = (tag, cls, html) => { const e = document.createElement(tag); if (cls) e.className = cls; if (html != null) e.innerHTML = html; return e; };
  const money = n => "$" + Number(n).toLocaleString("en-US");
  const esc = s => String(s).replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
  const REVIEWS = window.CHECKMATELA_REVIEWS || {};
  const stars = r => "★".repeat(Math.round(r)) + "☆".repeat(5 - Math.round(r));
  const avg = list => list.length ? list.reduce((a, r) => a + r.r, 0) / list.length : 0;

  /* ------------------------------------------------ dialogs (shared) */
  function dialog(cls) {
    const d = h("dialog", "shop-dialog " + cls);
    d.addEventListener("click", e => { if (e.target === d) d.close(); });
    document.body.appendChild(d);
    return d;
  }
  const qv = dialog("qv-dialog");
  const cmpDlg = dialog("cmp-dialog");

  /* ------------------------------------------------ Quick View + reviews */
  function openQuickView(card, root) {
    const id = card.dataset.id, name = card.dataset.name, tag = card.dataset.tag, price = card.dataset.price;
    const facets = JSON.parse(root.dataset.facets || "[]");
    const rfacets = JSON.parse(root.dataset.reviewFacets || "[]");
    const thumbs = $$(".gallery-thumb", card).map(b => b.dataset.src);
    const images = thumbs.length ? thumbs : [card.dataset.img];
    const reviews = (REVIEWS[id] || []).slice();
    const attrs = facets.map(f => [f.label, (card.dataset["f" + f.key[0].toUpperCase() + f.key.slice(1)] || "").split("|").filter(Boolean).join(", ")]).filter(a => a[1]);
    const kind = root.dataset.kind;
    const optionDefs = JSON.parse(root.dataset.options || "[]");
    const sizeNote = kind === "pawn" ? "Sizes 2T–14" : "Jackets 36–48 · trousers 28–40";
    const mail = `mailto:suit.shop.dtla@gmail.com?subject=${encodeURIComponent("Review: " + name)}&body=${encodeURIComponent("Product: " + name + " (" + tag + ")\nRating (1-5):\nTitle:\nYour review:\n" + rfacets.map(f => f[1] + ":\n").join(""))}`;

    qv.innerHTML = `
      <button class="shop-dialog__x" aria-label="Close">×</button>
      <div class="qv">
        <div class="qv__media">
          <img class="qv__main" src="${images[0]}" alt="${esc(name)}">
          ${images.length > 1 ? `<div class="qv__thumbs">${images.map((s, i) => `<button type="button" class="${i ? "" : "is-active"}" data-src="${s}"><img src="${s}" alt="" loading="lazy"></button>`).join("")}</div>` : ""}
        </div>
        <div class="qv__info">
          <span class="eyebrow">${esc(tag)}</span>
          <h2>${esc(name)}</h2>
          <p class="qv__price">${money(price)}</p>
          <p class="qv__rating"></p>
          <dl class="qv__attrs">${attrs.map(a => `<div><dt>${esc(a[0])}</dt><dd>${esc(a[1])}</dd></div>`).join("")}</dl>
          <div class="qv__opts">${optionDefs.map(o => `<fieldset class="qv-opt" data-key="${o.key}"><legend>${esc(o.label)}${o.required ? "" : ""}</legend><div class="qv-opt__chips">${o.values.map(v => `<button type="button" class="chip-btn" data-v="${esc(v)}" aria-pressed="${v === o.default}">${esc(v)}</button>`).join("")}</div></fieldset>`).join("")}</div>
          <p class="qv__size">${sizeNote} · <a class="link" href="size-guide.html">Size guide</a></p>
          <p class="qv__msg" role="status"></p>
          <div class="qv__cta"><button type="button" class="btn qv-add">Add to bag</button><a class="btn dark-ghost" href="book-a-fitting.html">Book a fitting</a></div>
        </div>
        <section class="reviews" aria-labelledby="rv-h"><h3 id="rv-h">Reviews</h3><div class="reviews__body"></div></section>
      </div>`;
    $(".shop-dialog__x", qv).onclick = () => qv.close();
    $$(".qv__thumbs button", qv).forEach(b => b.onclick = () => {
      $(".qv__main", qv).src = b.dataset.src;
      $$(".qv__thumbs button", qv).forEach(x => x.classList.toggle("is-active", x === b));
    });
    // options (size / length) + add to bag
    const chosen = {}; optionDefs.forEach(o => { if (o.default) chosen[o.key] = o.default; });
    $$(".qv-opt", qv).forEach(fs => $$(".chip-btn", fs).forEach(b => b.onclick = () => {
      $$(".chip-btn", fs).forEach(x => x.setAttribute("aria-pressed", "false")); b.setAttribute("aria-pressed", "true"); chosen[fs.dataset.key] = b.dataset.v; $(".qv__msg", qv).textContent = "";
    }));
    $(".qv-add", qv).onclick = () => {
      const missing = optionDefs.find(o => o.required && !chosen[o.key]);
      if (missing) { $(".qv__msg", qv).textContent = "Please choose a " + missing.label.toLowerCase() + "."; const fs = $(`.qv-opt[data-key="${missing.key}"]`, qv); fs.classList.remove("shake"); void fs.offsetWidth; fs.classList.add("shake"); return; }
      if (!window.CheckmatelaBag) { $(".qv__msg", qv).textContent = "The bag isn't available on this page."; return; }
      window.CheckmatelaBag.add({ id, name, tag, price: Number(price), img: card.dataset.img, options: Object.assign({}, chosen) });
      qv.close(); window.CheckmatelaBag.open();
    };
    renderReviews($(".reviews__body", qv), reviews, rfacets, mail, $(".qv__rating", qv));
    qv.showModal();
    qv.scrollTop = 0;
  }

  function renderReviews(box, all, rfacets, mail, ratingEl) {
    const sel = {}; let sort = "new";
    ratingEl.innerHTML = all.length ? `<span class="stars" aria-label="${avg(all).toFixed(1)} out of 5">${stars(avg(all))}</span> ${avg(all).toFixed(1)} <a href="#" class="link rv-jump">(${all.length} review${all.length > 1 ? "s" : ""})</a>` : `<span class="muted">No reviews yet</span>`;
    const jump = $(".rv-jump", ratingEl); if (jump) jump.onclick = e => { e.preventDefault(); box.scrollIntoView({ behavior: "smooth" }); };
    if (!all.length) {
      box.innerHTML = `<p class="muted">No reviews yet — be the first to share how it fits.</p><a class="btn small" href="${mail}">Write a review</a>`;
      return;
    }
    const fitVals = ["Runs small", "True to size", "Runs large"];
    const fitCounts = fitVals.map(v => all.filter(r => r.fit === v).length), fitTotal = fitCounts.reduce((a, b) => a + b, 0);
    const dist = [5, 4, 3, 2, 1].map(n => [n, all.filter(r => r.r === n).length]);
    const groups = rfacets.map(([k, label]) => [k, label, [...new Set(all.map(r => r[k]).filter(Boolean))]]).filter(g => g[2].length > 1);
    box.innerHTML = `
      <div class="rv-summary">
        <div class="rv-score"><b>${avg(all).toFixed(1)}</b><span class="stars">${stars(avg(all))}</span><small>${all.length} review${all.length > 1 ? "s" : ""}</small></div>
        <div class="rv-dist">${dist.map(([n, c]) => `<div><span>${n}★</span><i><u style="width:${(c / all.length) * 100}%"></u></i><span>${c}</span></div>`).join("")}</div>
        ${fitTotal ? `<div class="rv-fit"><h4>How it fits</h4><div class="rv-fit__bar">${fitCounts.map((c, i) => `<u style="flex:${c || 0.0001}" class="f${i}"></u>`).join("")}</div><div class="rv-fit__lbl">${fitVals.map((v, i) => `<span>${v} <em>${Math.round((fitCounts[i] / fitTotal) * 100)}%</em></span>`).join("")}</div></div>` : ""}
      </div>
      ${groups.length ? `<div class="rv-filters"><h4>Find reviews from people like you</h4>${groups.map(([k, label, vals]) => `<div class="rv-fgroup"><span>${esc(label)}</span>${vals.map(v => `<button type="button" class="chip-btn" data-k="${k}" data-v="${esc(v)}" aria-pressed="false">${esc(v)}</button>`).join("")}</div>`).join("")}</div>` : ""}
      <div class="rv-bar"><span class="rv-count"></span><label>Sort <select class="rv-sort"><option value="new">Newest</option><option value="hi">Highest rated</option><option value="lo">Lowest rated</option></select></label></div>
      <ul class="rv-list"></ul>
      <a class="btn small" href="${mail}">Write a review</a>`;
    const list = $(".rv-list", box), count = $(".rv-count", box);
    const paint = () => {
      let rows = all.filter(r => Object.entries(sel).every(([k, v]) => !v || r[k] === v));
      rows.sort((a, b) => sort === "hi" ? b.r - a.r : sort === "lo" ? a.r - b.r : b.d.localeCompare(a.d));
      count.textContent = rows.length === all.length ? `${all.length} reviews` : `${rows.length} of ${all.length} reviews`;
      list.innerHTML = rows.length ? rows.map(r => `
        <li class="rv">
          <div class="rv__head"><span class="stars">${stars(r.r)}</span><b>${esc(r.t)}</b>${r.sample ? `<em class="rv__sample">Sample review</em>` : ""}</div>
          <p>${esc(r.b)}</p>
          <div class="rv__meta"><span>${esc(r.n)}</span>${rfacets.map(([k, l]) => r[k] ? `<span>${esc(l)}: ${esc(r[k])}</span>` : "").join("")}<time>${r.d}</time></div>
        </li>`).join("") : `<li class="muted">No reviews match those filters.</li>`;
    };
    $$(".chip-btn", box).forEach(b => b.onclick = () => {
      const k = b.dataset.k, on = b.getAttribute("aria-pressed") !== "true";
      $$(`.chip-btn[data-k="${k}"]`, box).forEach(x => x.setAttribute("aria-pressed", "false"));
      b.setAttribute("aria-pressed", on ? "true" : "false");
      sel[k] = on ? b.dataset.v : null; paint();
    });
    $(".rv-sort", box).onchange = e => { sort = e.target.value; paint(); };
    paint();
  }

  /* ------------------------------------------------ compare */
  const tray = h("div", "cmp-tray"); tray.hidden = true; document.body.appendChild(tray);
  const picked = []; // {card, root}
  function renderTray() {
    tray.hidden = picked.length === 0;
    tray.innerHTML = `<div class="cmp-tray__in">
      <span class="cmp-tray__t">Compare <b>${picked.length}</b>/3</span>
      <div class="cmp-tray__items">${picked.map((p, i) => `<span class="cmp-chip"><img src="${p.card.dataset.img}" alt=""><em>${esc(p.card.dataset.name)}</em><button type="button" data-i="${i}" aria-label="Remove ${esc(p.card.dataset.name)}">×</button></span>`).join("")}</div>
      <button type="button" class="btn small cmp-go" ${picked.length < 2 ? "disabled" : ""}>Compare now</button>
      <button type="button" class="cmp-clear">Clear</button></div>`;
    $$(".cmp-chip button", tray).forEach(b => b.onclick = () => togglePick(picked[+b.dataset.i].card, picked[+b.dataset.i].root));
    $(".cmp-go", tray).onclick = openCompare;
    $(".cmp-clear", tray).onclick = () => { [...picked].forEach(p => togglePick(p.card, p.root)); };
  }
  function togglePick(card, root) {
    const i = picked.findIndex(p => p.card === card);
    if (i > -1) picked.splice(i, 1);
    else { if (picked.length >= 3) { picked.shift(); } picked.push({ card, root }); }
    $$("[data-id]").forEach(c => {
      const on = picked.some(p => p.card === c), b = $(".cmp-toggle", c);
      if (b) { b.setAttribute("aria-pressed", on ? "true" : "false"); b.textContent = on ? "✓ Comparing" : "+ Compare"; }
      c.classList.toggle("is-picked", on);
    });
    renderTray();
  }
  function openCompare() {
    const root = picked[0].root, facets = JSON.parse(root.dataset.facets || "[]");
    const cols = picked.map(p => p.card);
    const rows = [["Price", c => money(c.dataset.price)]];
    facets.forEach(f => { const key = "f" + f.key[0].toUpperCase() + f.key.slice(1); if (cols.some(c => c.dataset[key])) rows.push([f.label, c => esc((c.dataset[key] || "—").split("|").join(", "))]); });
    rows.push(["Rating", c => { const r = REVIEWS[c.dataset.id] || []; return r.length ? `<span class="stars">${stars(avg(r))}</span> ${avg(r).toFixed(1)} (${r.length})` : "—"; }]);
    cmpDlg.innerHTML = `<button class="shop-dialog__x" aria-label="Close">×</button>
      <h2 class="cmp-title">Compare</h2>
      <div class="table-wrap"><table class="compare-table compare-table--cards">
        <thead><tr><td></td>${cols.map(c => `<th scope="col"><div class="cmp-col"><img src="${c.dataset.img}" alt=""><b>${esc(c.dataset.name)}</b><span>${esc(c.dataset.tag)}</span></div></th>`).join("")}</tr></thead>
        <tbody>${rows.map(([l, fn]) => `<tr><th scope="row">${l}</th>${cols.map(c => `<td>${fn(c)}</td>`).join("")}</tr>`).join("")}
        <tr class="compare-cta"><td></td>${cols.map((c, i) => `<td><button type="button" class="btn small" data-i="${i}">Quick view &amp; reviews</button></td>`).join("")}</tr></tbody>
      </table></div>`;
    $(".shop-dialog__x", cmpDlg).onclick = () => cmpDlg.close();
    $$(".compare-cta button", cmpDlg).forEach(b => b.onclick = () => { cmpDlg.close(); openQuickView(cols[+b.dataset.i], root); });
    cmpDlg.showModal();
  }

  /* ------------------------------------------------ the shop (filters + sort) */
  function initShop(root) {
    const grid = $("[data-grid]", root);
    const facets = JSON.parse(root.dataset.facets || "[]");
    const noun = root.dataset.noun || "products", suffix = root.dataset.countSuffix || "";
    const cards = $$(":scope [data-grid] > [data-id]", root).map((el, i) => {
      const f = {};
      facets.forEach(fc => { f[fc.key] = (el.dataset["f" + fc.key[0].toUpperCase() + fc.key.slice(1)] || "").split("|").filter(Boolean); });
      return { el, i, name: el.dataset.name, price: +el.dataset.price, f };
    });
    const state = { sel: {}, min: null, max: null, sort: "featured" };
    facets.forEach(f => state.sel[f.key] = new Set());
    const prices = cards.map(c => c.price), pmin = Math.min(...prices), pmax = Math.max(...prices);
    const groups = facets.map(f => {
      const vals = [...new Set(cards.flatMap(c => c.f[f.key]))].sort();
      return { ...f, vals };
    }).filter(g => g.vals.length > 1);
    const hasPrice = pmin < pmax;

    const aside = $(".shop-filters", root), chips = $(".shop-chips", root), countEl = $(".shop-count", root);
    aside.innerHTML = `<div class="shop-filters__head"><b>Filters</b><button type="button" class="shop-clear">Clear all</button><button type="button" class="shop-filters__close" aria-label="Close filters">×</button></div>` +
      groups.map(g => `<details class="f-group" open data-key="${g.key}"><summary>${esc(g.label)}</summary><ul>${g.vals.map(v => `
        <li><label class="f-opt${g.swatch ? " f-opt--sw" : ""}"><input type="checkbox" data-key="${g.key}" value="${esc(v)}">${g.swatch ? `<i class="f-dot" style="--c:${SWATCH[v.toLowerCase()] || SWATCH.other}"></i>` : ""}<span>${esc(v)}</span><em data-count></em></label></li>`).join("")}</ul></details>`).join("") +
      (hasPrice ? `<details class="f-group" open><summary>Price</summary><div class="f-price"><label>Min<input type="number" inputmode="numeric" min="0" placeholder="${pmin}" data-price="min"></label><span>–</span><label>Max<input type="number" inputmode="numeric" min="0" placeholder="${pmax}" data-price="max"></label></div></details>` : "") +
      `<button type="button" class="btn shop-filters__apply">Show results</button>`;

    const passes = (c, skip) => {
      for (const g of groups) {
        if (g.key === skip) continue;
        const s = state.sel[g.key];
        if (s.size && !c.f[g.key].some(v => s.has(v))) return false;
      }
      if (state.min !== null && c.price < state.min) return false;
      if (state.max !== null && c.price > state.max) return false;
      return true;
    };
    const apply = () => {
      let shown = 0;
      cards.forEach(c => { const ok = passes(c); c.el.hidden = !ok; if (ok) shown++; });
      const sorters = { featured: (a, b) => a.i - b.i, "price-asc": (a, b) => a.price - b.price, "price-desc": (a, b) => b.price - a.price, name: (a, b) => a.name.localeCompare(b.name) };
      [...cards].sort(sorters[state.sort]).forEach(c => grid.appendChild(c.el));
      countEl.textContent = (shown === cards.length ? `${cards.length} ${noun}` : `Showing ${shown} of ${cards.length} ${noun}`) + suffix.replace(/&middot;/g, "·").replace(/&ndash;/g, "–");
      $(".shop-empty", root).hidden = shown !== 0;
      // dynamic option counts
      groups.forEach(g => $$(`input[data-key="${g.key}"]`, aside).forEach(inp => {
        const n = cards.filter(c => passes(c, g.key) && c.f[g.key].includes(inp.value)).length;
        const lab = inp.closest("label"); $("[data-count]", lab).textContent = `(${n})`; lab.classList.toggle("is-zero", n === 0 && !inp.checked);
      }));
      // chips
      const list = [];
      groups.forEach(g => state.sel[g.key].forEach(v => list.push([g.key, v, v])));
      if (state.min !== null || state.max !== null) list.push(["price", "", `${state.min !== null ? money(state.min) : money(pmin)} – ${state.max !== null ? money(state.max) : money(pmax)}`]);
      chips.innerHTML = list.length ? list.map(([k, v, t]) => `<button type="button" class="chip-btn is-on" data-k="${k}" data-v="${esc(v)}">${esc(t)} <span aria-hidden="true">×</span></button>`).join("") + `<button type="button" class="shop-clear">Clear all</button>` : "";
      const n = list.length; const fb = $(".shop-filter-btn__n", root); if (fb) fb.textContent = n ? `(${n})` : "";
      const ap = $(".shop-filters__apply", aside); if (ap) ap.textContent = `Show ${shown} result${shown === 1 ? "" : "s"}`;
    };
    const clearAll = () => { facets.forEach(f => state.sel[f.key].clear()); state.min = state.max = null; $$("input", aside).forEach(i => { if (i.type === "checkbox") i.checked = false; else i.value = ""; }); apply(); };

    aside.addEventListener("change", e => {
      const t = e.target;
      if (t.dataset.key) { const s = state.sel[t.dataset.key]; t.checked ? s.add(t.value) : s.delete(t.value); }
      else if (t.dataset.price) { const v = t.value === "" ? null : Math.max(0, +t.value); state[t.dataset.price] = v; }
      apply();
    });
    root.addEventListener("click", e => {
      const clr = e.target.closest(".shop-clear"); if (clr) { clearAll(); return; }
      const chip = e.target.closest(".shop-chips .chip-btn");
      if (chip) {
        const k = chip.dataset.k;
        if (k === "price") { state.min = state.max = null; $$("input[data-price]", aside).forEach(i => i.value = ""); }
        else { state.sel[k].delete(chip.dataset.v); $$(`input[data-key="${k}"]`, aside).forEach(i => { if (i.value === chip.dataset.v) i.checked = false; }); }
        apply(); return;
      }
      if (e.target.closest(".shop-filter-btn")) { const open = root.classList.toggle("filters-open"); e.target.closest(".shop-filter-btn").setAttribute("aria-expanded", open); return; }
      if (e.target.closest(".shop-filters__close, .shop-filters__apply")) { root.classList.remove("filters-open"); return; }
      const card = e.target.closest("[data-id]");
      if (!card || !grid.contains(card)) return;
      if (e.target.closest(".cmp-toggle")) { e.preventDefault(); togglePick(card, root); return; }
      if (e.target.closest(".gallery-thumb")) return;                 // thumbnails are handled by main.js
      if (e.target.closest(".product-card__quick, .card-reviews, .product-card__frame")) openQuickView(card, root);
    });
    $(".shop-sort", root).addEventListener("change", e => { state.sort = e.target.value; apply(); });
    apply();
  }

  $$("[data-shop]").forEach(initShop);
})();
