/* Homepage showcase — rotating product hero with a chessboard wipe.
   Markup is generated by tools/gen_home_showcase.py. */
(() => {
  "use strict";
  const root = document.getElementById('showcase');
  if (!root) return;

  const copies = [...root.querySelectorAll('.sc-copy')];
  const stages = [...root.querySelectorAll('.sc-figs')];
  const chips = [...root.querySelectorAll('.sc-chip')];
  const stage = root.querySelector('.sc-stage');
  const wipe = root.querySelector('.sc-wipe');
  const countEl = root.querySelector('.sc-count b');
  const N = stages.length;
  const reduce = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const DUR = parseFloat(getComputedStyle(root).getPropertyValue('--dur')) * 1000 || 7500;
  const pad = n => String(n + 1).padStart(2, '0');

  let cur = -1, busy = false, hover = false, focused = false, offscreen = false, tabHidden = false;
  let colorTimer = null;

  /* ---- lazy image loading ---- */
  const load = i => {
    const s = stages[((i % N) + N) % N];
    s.querySelectorAll('img[data-src]').forEach(img => { img.src = img.dataset.src; img.removeAttribute('data-src'); });
  };

  /* ---- kids' colourway cycling inside a Pawn slide ---- */
  const pawn = stage => {
    if (!stage.dataset.colors) return null;
    const colors = JSON.parse(stage.dataset.colors);
    const base = stage.dataset.base, m = colors.length;
    const slots = [...stage.querySelectorAll('.sc-fig')];
    const name = root.querySelector(`.sc-copy[data-i="${stage.dataset.i}"] .sc-colorname`);
    const dots = [...root.querySelectorAll(`.sc-copy[data-i="${stage.dataset.i}"] .sc-dot`)];
    let idx = +stage.dataset.start;
    const url = k => `${base}/${colors[((k % m) + m) % m].s}/hero.webp`;
    const set = k => {
      idx = ((k % m) + m) % m;
      slots.forEach(f => {
        const img = f.querySelector('img'), src = url(idx + +f.dataset.slot);
        if (img.getAttribute('src') === src) return;
        const pre = new Image();
        pre.onload = () => { f.classList.add('is-swap'); setTimeout(() => { img.src = src; f.classList.remove('is-swap'); }, 180); };
        pre.src = src;
      });
      if (name) name.textContent = colors[idx].n;
      dots.forEach((d, j) => d.classList.toggle('is-on', j === idx));
    };
    dots.forEach((d, j) => d.addEventListener('click', () => set(j)));
    return { next: () => set(idx + 1) };
  };
  const pawnCtl = stages.map(pawn);

  const startColors = i => {
    clearInterval(colorTimer);
    const c = pawnCtl[i];
    if (c && !reduce) colorTimer = setInterval(() => { if (!paused()) c.next(); }, 2100);
  };

  /* ---- state ---- */
  const paused = () => hover || focused || offscreen || tabHidden;
  const syncPaused = () => root.classList.toggle('is-paused', paused());

  const show = i => {
    cur = i;
    stages.forEach((s, k) => s.classList.toggle('is-active', k === i));
    copies.forEach((c, k) => c.classList.toggle('is-active', k === i));
    const cat = stages[i].dataset.cat;
    chips.forEach(ch => ch.classList.toggle('is-active', ch.dataset.cat === cat));
    // restart the progress line that drives auto-advance
    root.classList.remove('is-running'); void root.offsetWidth;
    if (!reduce) root.classList.add('is-running');
    if (countEl) countEl.textContent = pad(i);
    load(i); load(i + 1); load(i - 1);
    startColors(i);
  };

  /* ---- chessboard wipe ---- */
  let cells = 0, cols = 0, rows = 0;
  const buildWipe = () => {
    if (!wipe) return;
    const sr = root.getBoundingClientRect(), r = stage.getBoundingClientRect();
    const cell = parseFloat(getComputedStyle(root).getPropertyValue('--wipe')) || 84;
    const w = Math.ceil(sr.right - r.left), h = Math.ceil(r.bottom - sr.top);
    wipe.style.left = '0px';
    wipe.style.top = (sr.top - r.top) + 'px';
    wipe.style.width = w + 'px';
    wipe.style.height = h + 'px';
    wipe.style.right = 'auto';
    cols = Math.ceil(w / cell); rows = Math.ceil(h / cell);
    wipe.style.gridTemplateColumns = `repeat(${cols}, 1fr)`;
    wipe.style.gridTemplateRows = `repeat(${rows}, 1fr)`;
    wipe.innerHTML = '';
    for (let y = 0; y < rows; y++) for (let x = 0; x < cols; x++) {
      const i = document.createElement('i');
      if ((x + y) % 2) i.className = 'l';
      i.dataset.x = x; i.dataset.y = y;
      wipe.appendChild(i);
    }
    cells = cols * rows;
  };
  const STEP = 26;
  const setDelays = dir => {
    wipe.querySelectorAll('i').forEach(i => {
      const x = +i.dataset.x, y = +i.dataset.y;
      // wave travels bottom-left → top-right when going forward, the other way when going back
      const d = dir > 0 ? x + (rows - 1 - y) : (cols - 1 - x) + y;
      i.style.setProperty('--d', d * STEP + 'ms');
    });
    return (cols + rows - 2) * STEP + 300;
  };

  const go = (n, dir = 1, instant = false) => {
    n = ((n % N) + N) % N;
    if (busy || n === cur) return;
    if (reduce || instant || cur < 0 || !wipe || !cols) { show(n); return; }
    busy = true;
    const total = setDelays(dir);
    load(n);
    wipe.classList.add('cover');
    setTimeout(() => {
      show(n);
      setTimeout(() => {
        wipe.classList.remove('cover');
        setTimeout(() => { busy = false; }, total);
      }, 60);
    }, total + 40);
  };

  const next = () => go(cur + 1, 1);
  const prev = () => go(cur - 1, -1);

  /* ---- controls ---- */
  root.querySelectorAll('.sc-arrow').forEach(b => b.addEventListener('click', () => (+b.dataset.dir > 0 ? next() : prev())));
  chips.forEach(ch => ch.addEventListener('click', () => {
    const cat = ch.dataset.cat;
    // jump to the next slide of that category after the current one
    for (let k = 1; k <= N; k++) {
      const i = (cur + k) % N;
      if (stages[i].dataset.cat === cat) { go(i, i > cur ? 1 : -1); break; }
    }
  }));
  // auto-advance is driven by the progress bar finishing
  root.addEventListener('animationend', e => {
    if (e.animationName === 'scProgress' && !reduce && !busy) next();
  });
  root.addEventListener('mouseenter', () => { hover = true; syncPaused(); });
  root.addEventListener('mouseleave', () => { hover = false; syncPaused(); });
  root.addEventListener('focusin', () => { focused = true; syncPaused(); });
  root.addEventListener('focusout', () => { focused = false; syncPaused(); });
  document.addEventListener('visibilitychange', () => { tabHidden = document.hidden; syncPaused(); });
  root.addEventListener('keydown', e => {
    if (e.key === 'ArrowRight') { next(); } else if (e.key === 'ArrowLeft') { prev(); }
  });
  if ('IntersectionObserver' in window) {
    new IntersectionObserver(es => { offscreen = !es[0].isIntersecting; syncPaused(); }, { threshold: 0.25 }).observe(root);
  }
  // swipe
  let sx = null, sy = null;
  stage.addEventListener('pointerdown', e => { sx = e.clientX; sy = e.clientY; });
  stage.addEventListener('pointerup', e => {
    if (sx === null) return;
    const dx = e.clientX - sx, dy = e.clientY - sy; sx = null;
    if (Math.abs(dx) > 50 && Math.abs(dx) > Math.abs(dy) * 1.5) (dx < 0 ? next() : prev());
  });
  let rt;
  window.addEventListener('resize', () => { clearTimeout(rt); rt = setTimeout(buildWipe, 150); });

  /* ---- go ---- */
  buildWipe();
  show(0);
})();
