"""king.html ("Shop all men") is now generated by tools/gen_antonio.py together with the Antonio Uomo section: the King catalog in
tools/catalog/king.json became the Antonio Uomo product type "The Openings". This wrapper keeps the old command working:  python3 tools/gen_king_page.py
"""
import gen_antonio

if __name__ == "__main__":
    gen_antonio.main()
