"""Build the browser catalog from the King catalog and Pawn configuration.
Run after gen_king_page.py and gen_pawn_pages.py. No third-party parser or build server required.
"""
import re
import json
import html
from pathlib import Path
from gen_pawn_pages import LINES, ORDER

ROOT = Path(__file__).resolve().parent.parent
catalog = []
king = json.loads((ROOT / 'tools/catalog/king.json').read_text())['products']
for item in king:
    catalog.append(dict(id='king-'+item['slug'], name=item['name'], tag=item['tag'], category='King · Men', price=item['price'],
                        image=f"assets/img/products/{item['slug']}.jpg", page='king.html', sizes=['36R','38R','40R','42R','44R','46R'],
                        color=item['color'], pattern=item['pattern'], style=item['style'], occasion=item['occasion'],
                        description='A considered opening for weddings, celebrations, and evenings worth dressing for. Discover a silhouette with presence, from the first entrance to the last dance.'))
for line in ORDER:
    cfg = LINES[line]
    for color, label in cfg['colors']:
        base = f'assets/img/pawn/{line}/{color}'
        photos = [f'{base}/{p.name}' for prefix in ['model', 'plain'] for p in sorted((ROOT / base).glob(f'{prefix}-*.jpg'))]
        catalog.append(dict(id=f'pawn-{line}-{color}', name=f'{html.unescape(label)} {cfg["label"]}', tag=cfg['label'], category='Pawn · Kids',
                            price=cfg['price'], image=photos[0], images=photos, page=cfg['file'], sizes=['2T','3T','4','5','6','7','8','10','12','14'],
                            description='Small in scale. Big on presence. Discover the complete look, from every angle, for their next big moment.'))
concepts=[('bishop-bowtie','The Pin','Black bow tie',85,'bowtie','bishop.html','Bishop · Accessories',['One size']),
          ('bishop-pocketsquare','The Fianchetto','White pocket square',65,'pocketsquare','bishop.html','Bishop · Accessories',['One size']),
          ('bishop-cufflinks','The Zugzwang','Gold & onyx cufflinks',120,'cufflinks','bishop.html','Bishop · Accessories',['One size']),
          ('rook-shoes','The Castle','Black Oxford shoes',295,'shoes','rook.html','Rook · Shoes',['US 7','US 8','US 9','US 10','US 11','US 12','US 13'])]
for ident,name,tag,price,asset,page,category,sizes in concepts:
    catalog.append(dict(id=ident,name=name,tag=tag,price=price,image=f'assets/img/diagram/{asset}.png',page=page,category=category,sizes=sizes,
                        description='A finishing touch for the complete Checkmatela look. Concept imagery illustrates the planned collection; final materials and details are to be confirmed.',concept=True))
for page in ['bishop.html','rook.html']:
    path=ROOT/page;s=path.read_text(); cards=[]
    for p in [p for p in catalog if p['page']==page]:
        cards.append(f'''<a class="product-card" href="#{p['id']}" id="{p['id']}" data-product="{p['id']}"><div class="product-card__frame acc-frame"><img src="{p['image']}" alt="{p['tag']}" loading="lazy"><span class="product-card__notation">Concept piece</span><span class="product-card__quick"><span class="btn small">Explore the piece ↗</span></span></div><div class="product-card__meta"><div><h4>{p['name']}</h4><span class="piece-tag">{p['tag']}</span></div><span class="product-card__price">${p['price']}</span></div></a>''')
    s=re.sub(r'(<div class="product-grid"[^>]*>).*?(\n    </div>\n  </div>\n</section>)',lambda m:m.group(1)+'\n'+'\n'.join(cards)+m.group(2),s,count=1,flags=re.S)
    s=re.sub(r'(<span class="filter-bar__count">).*?(</span>)',lambda m:m.group(1)+f'{len(cards)} concept '+('pieces' if len(cards)>1 else 'piece')+m.group(2),s,count=1)
    path.write_text(s)
(ROOT / 'js/catalog.js').write_text('// Generated by tools/gen_catalog.py\nwindow.CHECKMATELA_CATALOG = '+json.dumps(catalog,ensure_ascii=False,indent=2)+';\n')
print(f'Generated {len(catalog)} catalog entries: 10 men, 34 kids, 4 concept accessories and shoes.')
